Feature/#96 develop facebook signup
yamujine/artmatch pull request #100
Opened 2017-02-17 06:20 UTC by Genie-Youn

Facebook 인증 후 회원가입 구현입니다.

- Facebook api를 통해  email과 profile_image를 받아온 후 signup page에 파리미터로 넘겨 채우는 식으로 구현했습니다.
- 페이스북 프로필 이미지의 타이틀 크기를 고려해서 profile_image column의 크기를 90으로 늘렸습니다.
ㅜㅜ

2017-02-17 07:15 UTC, kimtree commented on application/controllers/Account.php
> -		$this->twig->display('account/signup');
해당 페이지 내 indent 통일이 안되어 있는데 확인 부탁드립니다.

2017-02-17 07:16 UTC, kimtree commented on application/controllers/Account.php
> +	    if ($this->input->get('isFacebook')) {
isFacebook 파라미터가 없어도 그냥 email이나 picture 변수가 GET값으로 넘어오면 폼에 넣어줘도 되지 않을까요?

2017-02-17 07:18 UTC, kimtree commented on application/controllers/UsersApi.php
> +            if ($this->input->post('is_facebook') == TRUE) {
is_facebook 파라미터로 넘어오는 값을 정확히 체크하는게 좋습니다. html에서는 TRUE, FALSE로 넘기고 있던데 갼락하게 0,1로 변경하고 === '1' 또는  === '0'으로 strict하게 매치하는게 좋을 것 같습니다. ( 'TRUE'를 == TRUE와 비교하는 것은 좋지 않은 비교이고, 'TRUE'는 TRUE와 헷갈릴 수 있습니다. )

2017-02-17 07:18 UTC, kimtree commented on application/controllers/UsersApi.php
> +                $url = $this->input->post('profile_image');
$facebook_profile_image_url 등으로 명확한 변수명을 사용하면 좋을 것 같습니다.

2017-02-17 07:19 UTC, kimtree commented on application/libraries/Imageupload.php
> +        file_put_contents('./uploads/profile/'.$filename, file_get_contents($url));
'./uploads/profile/'.$filename 라는 부분이 두번 사용되는데 $profile_image_file_path 등으로 변수화시키면 좋을 것 같습니다.

2017-02-17 07:19 UTC, kimtree commented on application/libraries/Imageupload.php
> +    public function upload_facebook_image($url) {
실제로 함수가 하는 기능은 $url을 다운받아 저장하고 썸네일을 만드는 로직입니다. 함수명을 upload_profile_image_from_url 등으로 변경한다면, 추후에 프로필 이미지를 URL로 입력 받아 처리할 수도 있을 것 같습니다.

2017-02-17 07:22 UTC, kimtree commented on application/libraries/Imageupload.php
> +        $filename = substr($filename, 0, strrpos($filename, '?'));
파일 이름은 기존upload 라이브러리에서 encrypt name하는 것 처럼 암호화를 해서 저장하는 것이 좋을 것 같습니다. (혹시나 그렇진 않겠지만 파일명이 겹칠 수도 있고, 기존 우리가 이미지 파일 이름으로 저장하는 방식과 통일할 수 있습니다. 이러면 image 경로 저장을 위한 컬럼 길이를 늘일 필요도 없구요?)

2017-02-17 07:24 UTC, kimtree commented on application/views/account/login.twig
> +        appId      : '222831604846386',
appId는 어떻게 발급하셨나요? 이런 키 값들은 dev/prod 환경을 나누어서 config 파일 또는 환경변수로부터 불러오는 것이 좋습니다.

2017-02-17 07:25 UTC, kimtree commented on application/views/account/login.twig
> +        appId      : '222831604846386',
그리고 현재 본인을 제외한 계정에서는 테스트가 안되는 것 같은데, 확인 부탁드립니다.

2017-02-17 07:30 UTC, kimtree commented on application/views/account/login.twig
> +        console.log(response);
디버그 코드 제거 부탁드립니다.

2017-02-17 07:30 UTC, kimtree commented on application/views/account/login.twig
> +          console.dir(response);
디버그 코드 제거 부탁드립니다.

2017-02-17 07:42 UTC, kimtree commented on application/views/account/signup.twig
> +            <input type="text" name="profile_image" value = {{ picture }} />
value에 double quote 추가되어야 합니다.

2017-02-17 07:42 UTC, kimtree commented on application/views/account/signup.twig
> +          {% if picture %}
이 조건문은 그냥 값이 없으면 빈칸이 될테니 input type="hidden"을 출력할 때만 if를 쓰고 input type="text"에서는 그냥 value에 {{ picture }} 만 써도 문제 없습니다.

2017-02-17 07:44 UTC, kimtree requested changes
- 페이스북으로 인증을 하여 회원 가입은 가능하지만, 이미 가입된 회원인 경우에는 어떻게 인증을 하여 로그인 처리를 할 수 있는지요? 이 부분에 대한 구현이 빠져있는 것 같습니다.
 - 사용자의 UX에 대한 고민이 조금 필요합니다. 페이스북으로 회원 가입시 이미지 주소를 보여주는 것이 아니라 그냥 이미지 자체를 표시해 주는 것이 좀 더 사용자에게 명확할 것 같습니다.
 - 이미지 URL은 그냥 테스트 했을 때 정상 작동하는 것으로 보이는데, URL 요청시 뒤에 oh 파라미터를 제거하셨던 것은 아닌가요?

2017-02-17 07:45 UTC, kimtree commented on application/views/account/signup.twig
> +          {% if picture %}
사진이 있는 경우는 이미지를 바로 표시하고 이미지 URL은 hidden type으로 form submit하는 것이 좋을 것 같습니다.

2017-02-19 08:11 UTC, Genie-Youn commented on application/views/account/login.twig
> +        appId      : '222831604846386',
공개앱으로 전환하였습니다, 팀원분들 페이스북 계정 관리자로 등록하도록 하겠습니다.

2017-02-19 16:16 UTC, mintplo reviewed
일단 페이스북 회원가입만 구현하신 후 로그인은 따로 하실 예정이신가요?

페이스북 로그인 구현시 생각해봐야할 것이 있는데

페이스북으로 로그인 할 경우 해당 사용자가 픽아트유 서비스에 가입한 사용자인지 확인을 어떻게 할 것인가?

- 이 부분은 페이스북으로 가입할 때 페이스북 고유 ID를 같이 넘겨(숫자로 된 고유 번호) DB에 같이 저장한 후 로그인 시 이를 사용하여 처리하는 과정을 거치는데 현재 DB나 작성하신 코드를 보면 이를 나중에 대응하려고 생각 하셨거나 또는 누락하신 것으로 보이는데 확인 부탁드려요!

2017-02-20 03:33 UTC, Genie-Youn commented on application/controllers/Account.php
> -		$this->twig->display('account/signup');
done

2017-02-20 03:33 UTC, Genie-Youn commented on application/controllers/UsersApi.php
> +            if ($this->input->post('is_facebook') == TRUE) {
done

2017-02-20 03:33 UTC, Genie-Youn commented on application/controllers/UsersApi.php
> +                $url = $this->input->post('profile_image');
done

2017-02-20 03:33 UTC, Genie-Youn commented on application/libraries/Imageupload.php
> +        file_put_contents('./uploads/profile/'.$filename, file_get_contents($url));
done

2017-02-20 03:33 UTC, Genie-Youn commented on application/libraries/Imageupload.php
> +    public function upload_facebook_image($url) {
done

2017-02-20 03:34 UTC, Genie-Youn commented on application/libraries/Imageupload.php
> +        $filename = substr($filename, 0, strrpos($filename, '?'));
CI upload library가 encrypt 하는 것처럼 md5(uniqid(mt_rand()))로 encrypt 하였습니다

2017-02-20 03:35 UTC, Genie-Youn commented on application/views/account/login.twig
> +        console.log(response);
done

2017-02-20 03:35 UTC, Genie-Youn commented on application/views/account/login.twig
> +          console.dir(response);
done

2017-02-20 03:35 UTC, Genie-Youn commented on application/views/account/signup.twig
> +            <input type="text" name="profile_image" value = {{ picture }} />
done

2017-02-20 03:43 UTC, Genie-Youn commented
- 페이스북 url을 통한 회원가입시 이미지 파일명은 기존의 upload 라이브러리가 encrypt하는 방식으로 변경하였습니다.
- 현재 페이스북 로그인은 해당 이메일이 회원으로 존재하면 세션을 생성하여 바로 로그인하는 식으로 구현되어있습니다. 진만님 리뷰 반영해서 DB컬럼 추가후 페이스북 고유 id와 비교하여 로그인하도록 변경하는 작업은 별도 이슈로 분리하여 작업하도록 하겠습니다!

2017-02-20 03:45 UTC, Genie-Youn commented
페이스북 appId의 환경변수로 분리하는것은 도와주실수 있을까요?

2017-02-20 03:47 UTC, kimtree requested changes
별도 이슈 분리하지 않고 페이스북을 이용한 로그인 처리까지 일단 제대로 마무리 되었으면 좋겠습니다.

2017-02-20 03:47 UTC, kimtree commented on application/controllers/UsersApi.php
> +    public function check_facebook_email() {
어차피 facebook email도 유저 컬럼의 email 값으로 입력이 될텐데 이 함수가 필요한가요? 기존의 check_email api로는 불가한지요?

2017-02-20 03:47 UTC, kimtree commented on application/controllers/UsersApi.php
> +                $this->accountlib->generate_user_session($user->id);
이 부분은 실제 로그인 처리를 진행하는 것 같은데, 함수 이름과 그 목적이 맞지 않습니다. login_facebook 등의 네이밍이 되어야 할 것 같습니다.

2017-02-20 03:47 UTC, kimtree commented on application/controllers/UsersApi.php
> +                $user = $this->user_model->get_by_email($email);
이 부분은 페이스북으로 회원 가입한 사람의 이메일 주소만 알면 그 유저로 로그인이 가능하지 않을까요?

2017-02-20 03:47 UTC, kimtree commented on application/libraries/Imageupload.php
> +    public function upload_image_by_url($url) {
이 부분도 다른 함수처럼 url, thumbnail 생성여부, 폴더명까지 지정되면 좋을 것 같습니다.

2017-02-20 03:47 UTC, kimtree commented on application/libraries/Imageupload.php
> +        $file_ext = substr($file_ext, 0, strpos($file_ext, '?'));
아마 함수중에 해당 주소에서 쿼리스트링 또는 파일명 제거하는 깔끔한 방법이 있을 것 같은데 확인 부탁드립니다. ( http://stackoverflow.com/a/31476046/1439169 )

2017-02-20 03:47 UTC, kimtree commented on application/libraries/Imageupload.php
> +        return $filename;
성공 했을 경우에 $filename 실패했을 경우에는 empty string이 좋을 것 같습니다.

2017-02-20 03:47 UTC, kimtree commented on sql/scheme.sql
> +  `profile_image` VARCHAR(90) NOT NULL COMMENT '유저 프로필 이미지 파일 이름',
원래대로 45로 원복해도 될 것 같습니다.

2017-02-20 03:49 UTC, Genie-Youn commented on application/controllers/UsersApi.php
> +    public function check_facebook_email() {
해당 api에 페이스북 고유 id 비교등 추가 로직이 있을것 같아서 별도로 분리하였습니다!

2017-02-20 03:59 UTC, kimtree commented on application/controllers/UsersApi.php
> +    public function check_facebook_email() {
이런 경우는 이메일 체크, 고유 아이디 체크 따로 가야할 것이 아니라 기존 login() 함수 밑에 login_facebook() 등의 이름으로 된 함수를 만들어서 처리하는게 맞는 것 같습니다.

2017-02-20 04:01 UTC, Genie-Youn commented on application/controllers/UsersApi.php
> +    public function check_facebook_email() {
넵 반영하겠습니다.

2017-02-20 06:11 UTC, Genie-Youn commented
facebook 고유 id와 비교하여 로그인하도록 로직과 데이터베이스를 수정하였습니다.

2017-02-20 06:11 UTC, kimtree commented on application/controllers/UsersApi.php
> +        if ($this->input->post('isFacebook') === '1'){
isFacebook 파라미터는 다른 파라미터와 통일성을 위해 is_facebook으로 바꾸는 것이 좋을 것 같습니다.

2017-02-20 06:13 UTC, kimtree commented on application/libraries/Imageupload.php
> +        $image_path = self::UPLOAD_PATH.$image_type.'/'.$filename;
. 앞뒤로는 공백이 들어가야 합니다. self::UPLOAD_PATH . $image_type . '/' . $filename;

2017-02-20 06:19 UTC, kimtree commented on application/libraries/Imageupload.php
> +        $filename = $this->CI->security->sanitize_filename(md5(uniqid(mt_rand()))) .'.'.$file_ext;
uniqid 함수에서 prefix와 more entropy라고 analyzer에서 잡는데 확인 부탁드립니다.

2017-02-20 06:20 UTC, kimtree commented on application/libraries/Imageupload.php
> +        $result = file_put_contents($image_path, file_get_contents($url));
대신에 copy 함수를 사용하라고 analyzer에서 잡습니다. 애널라이저 결과도 확인해주세요.

2017-02-20 06:21 UTC, kimtree commented on application/views/account/login.twig
> +        appId      : '222831604846386',
음 app 계정은 픽아트유 페이지 관리하고 있는 대표 계정으로 생성하시는게 좋을 것 같습니다.

2017-02-20 06:26 UTC, Genie-Youn commented on application/libraries/Imageupload.php
> +        $result = file_put_contents($image_path, file_get_contents($url));
analyzer는 어떻게 확인하죠??!
<img width="500" alt="2017-02-20 3 25 25" src="https://cloud.githubusercontent.com/assets/16642635/23114186/dd077ac2-f780-11e6-942b-ab2ef28a75c6.png">

이부분 말씀하시는건가요?

2017-02-20 06:30 UTC, kimtree commented on application/libraries/Imageupload.php
> +        $result = file_put_contents($image_path, file_get_contents($url));
<img width="1360" alt="2017-02-20 15 28 44" src="https://cloud.githubusercontent.com/assets/557307/23114251/509de69c-f781-11e6-84bf-83a520b715d7.png">
<img width="1360" alt="2017-02-20 15 28 55" src="https://cloud.githubusercontent.com/assets/557307/23114258/59dfdef4-f781-11e6-9a02-129860949741.png">
아 이건 플러그인을 깔아서 그랬나.... PHP Inspections 라는 플러그인이 있네요;

2017-02-20 06:40 UTC, kimtree commented
@Genie-Youn 음 페이스북 로그인 같은 경우는 id/email 조합이 생각보다 취약합니다. ( http://findmyfbid.com/ 같은 서비스로 얻어낼 수 있습니다. 구현하신 방법으로는 id/email을 겉으로 사용하고 있는게 노출되어 있기 때문에 누구나 저 정보를 알면 로그인할 수 있습니다. ) 원래 흐름대로는 access token을 발급 받은 뒤에 back-end에서 해당 access_token으로 유저 정보를 가져온 다음에 내부적으로 처리를 해야 캡슐화가 될 수 있을 것 같은데....

https://www.sammyk.me/best-practice-for-facebook-login-with-the-javascript-sdk-and-php-sdk-v4-1 "Login With JavaScript And Get Access Token With PHP" 라는 내용도 잘 설명되어 있네요.

appId 사용하는 것은 환경변수는 아니고 https://codeigniter.com/userguide3/libraries/config.html 이거 사용하셔서 config.php에 넣으시면 될 것 같습니다. Twig 연동할 때는 $this->twig->addGlobal('session', $_SESSION); 이런식으로 변수 넣어주시면 됩니다.

2017-02-20 06:43 UTC, Genie-Youn commented on application/libraries/Imageupload.php
> +        $result = file_put_contents($image_path, file_get_contents($url));
오 좋네요!

2017-02-20 06:46 UTC, Genie-Youn commented
출근할시간이라 해당내용은 퇴근하고 다시 확인해보겠습니다.

2017-02-20 18:45 UTC, Genie-Youn commented on application/views/account/login.twig
> +        appId      : '222831604846386',
pickartyou 대표계정으로 생성하였습니다.

2017-02-21 02:13 UTC, kimtree approved these changes
현재 composer을 사용하지 않고 작업을 해왔는데요, composer 세팅 방법도 함께 공유해주시면 좋을 것 같습니다. 관련 vendor폴더 .gitignore 포함도요~

2017-02-21 02:13 UTC, kimtree commented on application/controllers/Account.php
> +        $this->twig->addGlobal('facebook_app_id', $this->config->item('app_id'));
상수처럼 쓰이는 변수명이니 대문자로 써 주세요.

2017-02-21 02:13 UTC, kimtree commented on application/controllers/Account.php
> +        $this->load->helper('url');
url 헬퍼는 어디쪽에서 쓰이나요?

2017-02-21 02:13 UTC, kimtree commented on application/controllers/UsersApi.php
> +        return $this->output->set_output(json_encode($this->result));
해당라인 return success response 함수 사용해주세요.

2017-02-21 02:13 UTC, kimtree commented on application/controllers/UsersApi.php
> +            $result = $this->user_model->check_email($email);
get email and fb id로 쿼리하면 하나의 쿼리로 결과를 쉽게 낼 수 있을 것 같습니다.

2017-02-21 02:13 UTC, kimtree commented on application/controllers/UsersApi.php
> +        } else {
early return 되므로 else 구문은 없어도 됩니다.

2017-02-21 02:13 UTC, kimtree commented on application/core/MY_Controller.php
> +        $this->twig->addGlobal('facebook_app_id', $this->config->item('app_id'));
상수 대문자 처리

2017-02-21 02:13 UTC, kimtree commented on composer.json
> +        "facebook/php-sdk-v4": "~5.0"
인덴트가 이상합니다.

2017-02-21 03:46 UTC, kimtree commented on application/controllers/Account.php
> +            if (isset($accessToken)) {
isset 보다는 !== null 체크가 좀 더 명확할 것 같습니다.

2017-02-21 03:49 UTC, kimtree commented on application/controllers/UsersApi.php
> +        if ($this->input->post('is_facebook') === '1') {
로그인 함수는 공통으로 하고 안에서 facebook 여부에 따라서 _simple_login / _facebook_login 등으로 분리되면 좋을 것 같습니다. (여기에 있는 facebook 관련 로직도 _login_facebook 함수 내로)

2017-02-21 03:51 UTC, kimtree commented on application/libraries/Imageupload.php
> +        } else {
result가 === false인 경우 ''을 먼저 리턴하고 else 없이 thumbnail 생성 로직과 return $filename도 깔끔해 보입니다.

2017-02-21 03:54 UTC, kimtree commented on application/views/account/login.twig
> +            return window.location = '/account/signup?' + $.param(param);
여기도 그냥 location.href쓰면 되지 않으려나요?

2017-02-21 03:54 UTC, mintplo commented on application/controllers/Account.php
> +            if (isset($accessToken)) {
http://php.net/manual/kr/function.isset.php

변수 또는 Object set 또는 Array 안의 속성이 설정되었는지 사용하는 용도입니다.

이미 상단에서 변수가 설정이 되었으니 isset 보다는 @kimtree 님께서 말씀하신 방법으로 처리하는 것이 좋을것 같아요.

2017-02-21 03:56 UTC, kimtree commented on application/views/account/signup.twig
> +          <input type="text" name="email" placeholder="이메일" onkeyup="checksEmail()" {% if email %} value = "{{ email }}" {% endif %}/>
facebook 로그인인 경우 email은 readonly로 해서 고정해야 할 것 같습니다. 나중에 facebook 아이디와 이메일로 인증 체크를 하니까 변경되면 안될 것 같습니다. 근데 만약에 페이스북 사용자가 자기 대표 이메일을 변경하면 어떻게 되려나요;;

2017-02-21 03:57 UTC, kimtree requested changes
코멘트를 참조해주세요.

2017-02-21 05:22 UTC, Genie-Youn commented on application/controllers/Account.php
> +        $this->load->helper('url');
url 헬퍼는 기존에 있던칭구라 일단은 제거하겠습니다~

2017-02-21 05:34 UTC, Genie-Youn commented on application/controllers/Account.php
> +            if (isset($accessToken)) {
아 그렇군요 감사합니다.

2017-02-21 05:35 UTC, Genie-Youn commented on application/views/account/signup.twig
> +          <input type="text" name="email" placeholder="이메일" onkeyup="checksEmail()" {% if email %} value = "{{ email }}" {% endif %}/>
readonly로 변경하겠습니다~

2017-02-21 05:35 UTC, Genie-Youn commented on composer.json
> +        "facebook/php-sdk-v4": "~5.0"
composer.json은 탭으로 되어있군요

2017-02-21 05:47 UTC, Genie-Youn commented on application/controllers/Account.php
> +        $this->load->helper('url');
이메일인증할때 redirect에서 사용되네요 다시 추가하겠습니다!

2017-02-21 06:09 UTC, Genie-Youn commented
composer 세팅 방법은 wiki에 정리해두면 될까요?

2017-02-21 14:37 UTC, kimtree requested changes

2017-02-21 14:37 UTC, kimtree commented on application/controllers/UsersApi.php
> +        $email_or_username = $this->input->post('email_or_username');
아마 여기서 input 안받고 _simple_login에서 $this->input으로 받아올 수 있지 않나요?'

2017-02-21 14:37 UTC, kimtree commented on application/controllers/UsersApi.php
> +        $user = $this->user_model->get_email_and_fb_id($userNode->getEmail());
아 제 생각은 email과 fb_id가 where절로 선택해서 값을 가져오는 걸 생각했는데요! 이러면 이메일만 있으면 그 유저처럼 fb id까지 가져올 수 있으니까요~

2017-02-21 14:37 UTC, kimtree commented on application/controllers/Account.php
> +        $this->load->helper('url'); //email verify redirect
원래 위치에 넣고 주석 지우면 diff에 추가/삭제된 것으로 안뜨니까 신경 안쓸 수 있을 것 같습니다.

2017-02-21 14:38 UTC, kimtree commented on application/controllers/UsersApi.php
> +
빈줄 제거 부탁드립니다.

2017-02-21 14:43 UTC, kimtree commented on application/views/account/login.twig
> +      FB.login(function(response) {
테스트 해보니 FB.login이 오류가 나는 경우에도 아래 /api/login 으로 ajax 요청이 날아가서 오류가 뜨는데, FB.login이 정상적일 때만 /api/login의 ajax 요청이 들어가야 할 것 같습니다.

2017-02-21 16:57 UTC, kimtree commented on application/controllers/UsersApi.php
> +        $this->_simple_login();
if~else 구문으로 해주세요. 만약에 facebook login에서 die가 호출이 안되면 밑에 simple_login도 순서대로 실행될 위험이 있습니다.

2017-02-21 16:57 UTC, kimtree commented on application/views/account/login.twig
> +        console.dir(response);
디버깅 코드 제거해주세요.

2017-02-21 17:01 UTC, kimtree commented on application/config/facebook.php
> +$config['app_id'] = '173033269864660';
아 생각해보니까 git에 이거 커밋되면 안될 것 같네요;; 보안에 문제가 생길 수가 있어서요. database처럼 $_ENV 방식 또는 이 파일에서 app_id와 app_secret 값만 일단 비워둔 상태로 커밋하는게 좋을 것 같습니다.

2017-02-21 17:01 UTC, kimtree requested changes
if~else 로직 관련 중요한 수정이라서 일단 보류합니다. 그리고 개발환경에서는 페이스북 관련 연동이 테스트가 잘 안되는데 테스트 방법 소개 부탁드립니다.

2017-02-21 17:11 UTC, Genie-Youn commented
혹시 localhost 포트가 어떻게 되세요?

2017-02-21 17:20 UTC, Genie-Youn commented
테스트해본결과 localhost는 특정 포트 하나만 url로 등록이 가능한것 같습니다. 현재는 localhost:3000만 등록이 된 상태라 나머지는 '앱 도메인에 포함되어 있지 않은 URL입니다.' 라는 메세지가 나오는것 같네요

2017-02-22 02:28 UTC, kimtree commented
localhost 8080인데 변경하고 해봐야겠네요.

2017-02-22 05:49 UTC, kimtree commented
## UI
- login.twig에서 페이스북 -> 페이스북으로 로그인하기 등으로 네이밍 변경되면 좋을 것 같습니다.

## 로그인 & 회원가입 정책
- 페이스북 회원가입시 이메일이 readonly임. 그러나 중복된 이메일이 있는 경우는 가입할 방법이 전혀 없습니다. (아마 이메일 값은 버리고 API로 받아온 facebook_id로만 가입체크를 해아할지..)
- 페이스북 회원 가입시 가입 인증 이메일 발송되는 것 같은데, 페이스북 회원 가입자는 가입 인증 없이 바로 인증처리 하는 것도 좋을 것 같습니다.
- 페이스북 로그인 창에서 [수정] -> 이메일 [체크 해제] -> 진행시 이메일 주소가 입력되어 있지 않습니다 오류 -> 그 다음에 앱 삭제하고 다시 인증할 때 까지 방법이 없는데 좋은 방법 없을까요?

## composer
- composer 세팅/ 배포 관련 내용 위키 추가 및 .gitignore 추가
<img width="792" alt="2017-02-22 14 33 17" src="https://cloud.githubusercontent.com/assets/557307/23198608/1bea9620-f90c-11e6-993d-9e8232ede872.png">
- composer install 실행시 다음과 같이 구 라이브러리라고 오류 뜹니다. 업데이트 해주세요.
- composer.lock 파일 commit해주세요.

* 항상 말씀드리지만 제 의견은 개인적인 의견일 뿐 답은 아닙니다! 본인이 사용할 사용자 중심의 서비스를 만든다고 생각해 보시고 관련 플로우도 함께 점검되면 좋을 것 같습니다.

2017-02-23 06:17 UTC, Genie-Youn commented
페이스북 로그인시 기존의 가입한 이메일이면 facebook_id만 추가하도록 변경

2017-02-23 07:43 UTC, kimtree commented on .gitignore
> +/composer.phar
이건 본인이 설치한 파일 아닌가요? composer가 system-wide로 설치되면 따로 composer.phar 파일을 여기에 두고 실행하지는 않을 것 같습니다.

2017-02-23 07:43 UTC, kimtree commented on application/config/facebook.php
> +$config['app_id'] = '';
$_ENV['FB_APP_ID'] 등으로 가져올 수 있으면 이게 좋겠네요.

2017-02-23 07:47 UTC, kimtree commented on application/controllers/Account.php
> +                'default_graph_version' => 'v2.5'
v2.8이 최신입니다. v2.5를 꼭 써야하는 이유가 없다면 가급적 최신 버젼으로 유지해주세요.

2017-02-23 07:48 UTC, kimtree commented on application/controllers/UsersApi.php
> +            $is_already_used = $this->user_model->check_email($userNode->getEmail());
email 보다는 fb_id로 체크하는게 정확하지 않나요? 이메일은 변경될 수 있다는 것을 예상해야 할 것 같습니다.

2017-02-23 07:49 UTC, kimtree commented on application/controllers/UsersApi.php
> +                    $this->return_fila_response(['message' => 'facebook verify fail']);
fila 오타입니다.

2017-02-23 07:50 UTC, kimtree commented on application/controllers/UsersApi.php
> +        if ($user->facebook_id !== $userNode->getId()) {
위에서 user을 $userNode->getId()의 facebook_id로 가져왔는데 둘이 다를 수가 있나요?

2017-02-23 08:01 UTC, kimtree commented on application/views/account/login.twig
> +          $('.facebook').attr('disabled', true);
여러개 테스트 해봤는데, 재 시도의 여지를 주기 위해서 페이스북 로그인을 disable하지는 않아도 될 것 같습니다.

2017-02-23 08:22 UTC, kimtree commented on application/views/account/login.twig
> +        if (response.status !== 'connected') {
자세히 찾아보니 3가지 경우가 있는 것 같습니다.
- 그냥 창 끄기
- 인증했는데 이메일 권한 빼기
- 정상

# 처리 방안 
  - 그냥 창 끄는 경우는 disabled만 없애면 될 것 같습니다. + alert 페이스북 로그인에 실패했습니다.
  - 인증 했는데 권한은 -> /me/permissions(FB API) 에 email이 없으면 (또는) /api/login 보내서 확인 후 없으면 -> 이메일 권한이 필요합니다. 알려주고 재 인증 요청 ( 권한 추가 파트 확인 https://developers.facebook.com/docs/facebook-login/web/permissions )

2017-02-23 08:27 UTC, kimtree requested changes
거의 다 온 것 같습니다! 권한 없는 경우 추가 권한 요청 관련 메세지 처리와 로그인 확인시 정책이 좀 필요할 것 같습니다.
개인적 의견은 아래와 같습니다.

# FB id로만 체크
  - 이미 가입된 fb 유저가 있으면 -> 로그인 처리
  - 이미 가입된 fb 유저가 없으면 -> 이메일 등 정보 입력된 상태로 가입화면으로 넘어감 (여기서 당연히 이메일 중복 체크) - 기존에 가입된 이메일이 있으면 update가 아니라 그냥 다른 이메일 선택하도록

왜냐하면 현재 로직상에서는 제가 a@a.com 으로 가입했는데 누군가가 a@a.com으로 페이스북 프로필에 설정하고 페이스북으로 로그인하면 제 계정을 다른사람이 페이스북 로그인으로 손쉽게 로그인 할 수 있다는 큰 문제점이 생기기 때문입니다.

일단 개인적인 의견이기 때문에 자세한 것은 기획자 분들께 여쭈어보는 것도 좋을 것 같습니다.

2017-02-23 20:07 UTC, Genie-Youn commented
- 인증한뒤 이메일권한을 빼서 로그인이 올바르게 되지 않을경우 권한 재요청을 하도록 변경하였습니다.
- 페이스북 로그인시 Facebook id로만 체크하도록 변경하였습니다.
- 페이스북 회원가입시 해당 이메일이 이미 가입된 이메일이면 readonly를 풀고 중복된 메일이라는 메세지를 보여주어 이메일을 변경하도록 하였습니다.
- 초기 update로 작성한 이유는 이미 우리 서비스를 통해 가입한 회원이 이걸 잊고 페이스북 로그인 버튼을 눌러 로그인 했을시 facebook 인증을 붙이기 위함이였는데 @kimtree 남우님이 말씀하신 방법으로 악용할 소지가 있을것같아 변경하였습니다.
- facebook button의 disable속성을 제거하였습니다.

2017-02-24 06:06 UTC, kimtree commented on application/views/account/login.twig
> +        version    : 'v2.8'
API 버젼 따로 config에 넣으셨던데 여기도 Twig 상수로 함께 연결해주면 좋을 것 같습니다.

2017-02-24 06:07 UTC, kimtree commented on application/views/account/login.twig
> +        if (response.data[i].permission === 'email') {
if문 하나로 email && declined 체크할 수 있을 것 같습니다.

2017-02-24 06:18 UTC, kimtree commented on application/views/account/signup.twig
> +    $(document).ready(function () {
이미 onkeyUp에 해당 함수 호출하는게 구현이 되어 있는거 같은데 ready에도 별도로 필요한가요?

2017-02-24 06:19 UTC, kimtree commented on application/views/account/signup.twig
> +          <input type="text" name="email" placeholder="이메일" onkeyup="checksEmail()" {% if email %} value = "{{ email }}" {%  if not duplicated_email %} readonly {% endif %} {% endif %}/>
if문 보기가 조금 불편한데 value="{{ email }}은 파라미터 없으면 알아서 아무것도 안뜰테니 if문 없어도 될 것 같습니다.

2017-02-24 06:23 UTC, kimtree commented on application/views/account/signup.twig
> +          <input type="text" name="email" placeholder="이메일" onkeyup="checksEmail()" {% if email %} value = "{{ email }}" {%  if not duplicated_email %} readonly {% endif %} {% endif %}/>
readonly는 더 깔끔하게 보이려면 input type hidden으로 메일주소 넣고, 프로필 이미지처럼 이메일 주소 그냥 텍스트로 찍어 줘도 좋을 것 같습니다.

2017-02-24 08:00 UTC, Genie-Youn commented on application/views/account/signup.twig
> +    $(document).ready(function () {
페이스북 인증을 통한 회원가입시 email이 입력된 상태로 넘어가는데 해당 인풋박스를 건드리지 않으면 이메일 체크를 하지 않기때문에 강제적으로 한번 실행시켜 사용자에게 메세지를 보여주는것이 좀 더 직관적이라고 생각했습니다!

2017-02-24 08:13 UTC, kimtree commented on application/views/account/signup.twig
> +    $(document).ready(function () {
email 입력되고 중복 안된 상태면 readonly로 뜨지 않나요? 검증이 의미가 있는지...
중복된 상태면 초기에 중복 되었다고 메세지를 먼저 표시할 수 있을 것 같구요.

2017-02-24 08:19 UTC, Genie-Youn commented on application/views/account/signup.twig
> +    $(document).ready(function () {
```javascript
{% if duplicated_email %}
  $(document).ready(function () {
    document.getElementById("warningEmail").innerText = "중복된 이메일 주소입니다.";
  });
{% endif %}
```

이런식으로 변경하는게 나으려나요?

2017-02-24 08:22 UTC, kimtree commented on application/views/account/signup.twig
> +    $(document).ready(function () {
@Genie-Youn 
```html
<div id="warningEmail">{% if duplicated_email %}중복된 이메일 입니다.{% endif %}</div>
```
그냥 이거만 넣으면 되는거 아닌가요?? js를 꼭 써야하는지... 어차피 onkeyup되면 js가 그때 부터 string 변경할꺼구요.

2017-02-24 08:28 UTC, Genie-Youn commented on application/views/account/signup.twig
> +    $(document).ready(function () {
확인했습니다.

2017-02-24 08:40 UTC, kimtree commented on application/views/account/signup.twig
> +            <input type="hidden" name="email" placeholder="이메일" onkeyup="checksEmail()" value = "{{ email }}" />
hidden type이므로 placeholder, onkeyup빠져도 됩니다.

2017-02-24 08:40 UTC, kimtree commented on application/views/account/signup.twig
> +            <div id="warningEmail" style = "color: red;">중복된 이메일 입니다.</div>
스타일 내용은 추후 마크업 쪽에 위임하는게 나을 것 같습니다. 지금은 메세지만 넣어주세요.

2017-02-24 09:09 UTC, kimtree requested changes
코멘트 확인 부탁드립니다.

2017-02-24 09:09 UTC, kimtree commented on application/controllers/UsersApi.php
> +            $this->return_fail_response('102', ['message' => '이메일을 찾을 수 없습니다.']);
fb_id로 유저 여부를 가져오는 것이기 때문에 잘못된 오류 메세지로 보입니다.

2017-02-24 09:09 UTC, kimtree commented on application/controllers/UsersApi.php
> +        $response = $fb->get('/me?fields=id,email');
email 정보는 가져오지 않아도 되지 않나요?

2017-02-24 09:09 UTC, kimtree commented on application/core/MY_Controller.php
> +        $this->twig->addGlobal('FACEBOOK_API_VERSION', $this->config->item('api_version'));
Account외에 페이스북 관련 로직을 사용하는게 아직 없는데 여기 추가되는 코드들은 제거해도 될 것 같습니다.

2017-02-24 09:09 UTC, kimtree commented on application/views/account/login.twig
> +          is_facebook:1
param이 하나니까 ajax->data에 그냥 넣어도 될 것 같습니다.

2017-02-24 09:09 UTC, kimtree commented on application/views/account/login.twig
> +        }
여기서 break 해주면 불필요하게 모든 permission을 순회할 필요가 없어집니다.

2017-02-24 09:09 UTC, kimtree commented on application/views/account/signup.twig
> +            <input type="hidden" name="email" placeholder="이메일" onkeyup="checksEmail()" value = "{{ email }}" />
placeholder, onkeyup 등 불필요한 attr들 삭제가 안되었습니다.

2017-02-24 09:09 UTC, kimtree commented on application/views/account/signup.twig
> +            <div style="text-align: left"> {{ email }} </div>
style은 일단 제거해주세요. 마크업에서 클래스 등으로 처리해주실껍니다.

2017-02-24 09:09 UTC, kimtree commented on application/controllers/Account.php
> +                $data['picture'] = $userNode->getPicture()->getUrl();
picture -> profile_image_url 등으로 url임을 알 수 있는 변수명이 필요합니다.

2017-02-24 13:43 UTC, kimtree approved these changes

2017-02-24 13:47 UTC, merged