Feature/#56 add pick on artwork detail
yamujine/artmatch pull request #103
Opened 2017-02-17 11:29 UTC by Nablyy

- 작품 상세 페이지 pick기능 구현
- pick 여부 확인 가능

리뷰 부탁드립니다!

2017-02-17 13:24 UTC, junho85 approved these changes
👍

2017-02-17 14:57 UTC, kimtree requested changes

2017-02-17 14:57 UTC, kimtree commented on application/controllers/Artworks.php
> +        $data['pickStatus'] = $pickStatus;
다른 변수명과 일관성 유지를 위해서 is_pick , pick_status 등으로 네이밍해주시면 좋을 것 같습니다.

2017-02-17 14:57 UTC, kimtree commented on application/models/Pick_model.php
> +            ->count_all_results();
user_id와 artwork_id로 검색하는 경우는 count가 1인 경우가 정상으로 알고 있는데, count === 1 인 경우 true를 리턴하는 함수로 만들어도 좋을 것 같습니다.

2017-02-17 14:57 UTC, kimtree commented on application/views/artworks/detail.twig
> +                if (data.result === true) {
API에 설계된 대로 리턴된 on, off 값을 이용한 로직으로 설계되면 나중에 마크업 입히고 난 이후에 쉽게 적용할 수 있을 것 같습니다.

2017-02-17 14:57 UTC, kimtree commented on application/config/routes.php
> +$route['api/pick']['POST'] = 'pickapi/index';
form submit 때문에 POST를 따로 지정해주신건지 모르겠지만 기본적으로 지정하지 않으면 /index를 호출하게 되니까 별도로 추가 안해도 될 것 같습니다.

2017-02-18 03:01 UTC, junho85 commented on application/config/routes.php
> +$route['api/pick']['POST'] = 'pickapi/index';
저거 추가 하고
if ($this->input->method() === 'post') { 검사를 제거 한거 같습니다.
둘 중 하나는 살려야 될 듯 한데 route 에서 post 로 제한 할 수 있다면 요 방법이 좋을 거 같습니다. 그런데 뒤에 /index 가 필요 한지는 모르겠네요.

2017-02-18 04:41 UTC, Nablyy commented on application/config/routes.php
> +$route['api/pick']['POST'] = 'pickapi/index';
/index 없어도 되네요! 제거했습니다~

2017-02-18 05:00 UTC, Nablyy commented on application/controllers/Artworks.php
> +        $data['pickStatus'] = $pickStatus;
반영했습니다~

2017-02-18 05:00 UTC, Nablyy commented on application/models/Pick_model.php
> +            ->count_all_results();
반영했습니다~

2017-02-18 05:01 UTC, Nablyy commented on application/views/artworks/detail.twig
> +                if (data.result === true) {
on, off값 이용해서 로직을 짜보긴 했는데 원하신 방향이 맞는지는 모르겠네요ㅜ

2017-02-18 05:59 UTC, merged