작품 댓글 달기 및 댓글 리스트 가져오기
yamujine/artmatch pull request #138
Opened 2017-02-20 14:01 UTC by junho85

2017-02-20 14:19 UTC, kimtree commented on application/views/artworks/detail.twig
> +            if (data.result == false) {
data.result => !data.result로 간단히 써도 될 것 같습니다.

2017-02-20 14:19 UTC, kimtree commented on application/views/artworks/detail.twig
> +            location.reload(true);
등록 실패한 경우 reload가 필요한가요?!

2017-02-20 14:20 UTC, kimtree commented on application/views/artworks/detail.twig
> +      {#{% if place.use_comment == 1 %}#}
댓글 사용 여부에 따라서 이 if 조건문이 활성화 될텐데, js는 그냥 놔두고 twig에서 입력 폼만 안보이게 할지 js랑 입력폼 다 가릴지 확인 부탁드립니다.

2017-02-20 14:21 UTC, kimtree commented on application/views/artworks/detail.twig
> +        <div class="title">댓글 <span class="number">3</span></div>
댓글 count 변수 처리 TODO 또는 comment api에서 재설정 등 고려 부탁드립니다.

2017-02-20 14:21 UTC, kimtree commented on application/views/artworks/detail.twig
> +                <img src="/static/images/tom.jpg" class="img-circle"/>
유저 이미지 표시할 수 있도록 API 리턴 부탁드립니다.

2017-02-20 14:22 UTC, kimtree commented on application/views/artworks/detail.twig
> +        <input type="hidden" name="type" placeholder="" value="artwork">
artwork 상수 사용하면 좋을 것 같습니다. TYPE_ARTWORK

2017-02-20 14:22 UTC, kimtree requested changes
리뷰 코멘트 확인 부탁드립니다.

2017-02-20 14:30 UTC, kimtree commented on application/controllers/Artworks.php
> +            $comments = $this->comment_model->get_comments_by_type_id('artwork', $artwork_id);
TYPE_ARTWORK 상수 사용 부탁드립니다.

2017-02-20 19:16 UTC, mintplo commented on application/views/artworks/detail.twig
> +            location.reload(true);
이 코드는 등록 성공한 경우만 새로고침 합니다.

2017-02-20 19:16 UTC, mintplo commented on application/views/artworks/detail.twig
> +      {#{% if place.use_comment == 1 %}#}
댓글 입력폼도 상세 공통이니 나중에 JS 파일로 분리시켜 <script src=""></script> 한 줄만 로드할지 말지로 만들면 좋을것 같습니다.

2017-02-21 03:45 UTC, kimtree commented on application/views/artworks/detail.twig
> +            location.reload(true);
아, 착각했네요. API 방식의 이점으로는 페이지 refresh 없이 자연스럽게 처리되는 것이라 생각했는데, 새로고침이 들어가서 조금 불편할 것 같습니다.

2017-02-21 03:57 UTC, mintplo commented on application/views/artworks/detail.twig
> +            location.reload(true);
마크업 입히기전에 작업하신 코드이고 이제 마크업이 입혀졌으니 다른 이슈로 등록하여 작업하시면 될것 같습니다!

@Nablyy @junho85

2017-02-21 13:29 UTC, junho85 commented on application/views/artworks/detail.twig
> +            location.reload(true);
이슈 생성 하였습니다. https://github.com/yamujine/artmatch/issues/155

2017-02-21 13:39 UTC, junho85 commented on application/views/artworks/detail.twig
> +      {#{% if place.use_comment == 1 %}#}
음. 일단 주석 처리 된 거 풀겠습니다. 일단 별도 이슈로 만들어 두겠습니다.
https://github.com/yamujine/artmatch/issues/156

2017-02-21 13:41 UTC, junho85 commented on application/views/artworks/detail.twig
> +        <div class="title">댓글 <span class="number">3</span></div>
https://github.com/yamujine/artmatch/issues/157 일단 이슈 생성

2017-02-21 13:59 UTC, junho85 commented on application/views/artworks/detail.twig
> +                <img src="/static/images/tom.jpg" class="img-circle"/>
작품, 댓글 모두 user_model 에서 가져와서 하도록 수정. join 걸면 좋은데 그건 TODO 로 주석 달아 둠.

2017-02-21 14:01 UTC, junho85 commented on application/views/artworks/detail.twig
> +        <input type="hidden" name="type" placeholder="" value="artwork">
TYPE_ARTWORKS

2017-02-21 14:03 UTC, junho85 commented on application/views/artworks/detail.twig
> +        <input type="hidden" name="type" placeholder="" value="artwork">
음. 그런데 TYPE_ARTWORKS 는 artwork 가 아니고 artworks 로 되어 있음. Comment_model 도 수정

2017-02-21 14:09 UTC, junho85 commented on application/views/artworks/detail.twig
> +        <input type="hidden" name="type" placeholder="" value="artwork">
comment 쪽에 artwork, place 로 된 부분들도 다 TYPE_ARTWORKS, TYPE_PLACES 로 변경

2017-02-21 14:12 UTC, junho85 commented on application/views/artworks/detail.twig
> +        <input type="hidden" name="type" placeholder="" value="artwork">
pick 쪽도 수정

2017-02-21 14:13 UTC, junho85 commented
코드 리뷰 내용 반영 하였습니다.

2017-02-21 14:13 UTC, merged