Add a feature to edit comment on artwork detail
yamujine/artmatch pull request #182
Opened 2017-02-22 07:19 UTC by Nablyy

작품 코멘트 수정 기능을 추가했습니다.
고민 중인게

- parent나 closest 를 사용해서 찾지말고 각 코멘트 id에 따라 폼에 id를 주는 방식으로 알맞는 폼을 찾아 사용할까?

입니다.
리뷰해주시면 감사하겠습니다~

2017-02-22 07:33 UTC, Nablyy commented
#142

2017-02-22 08:56 UTC, kimtree requested changes
아마 마크업 나오는거 따라서 코드가 좀 변경될 수 있을 것 같은데요, 일단 이정도면 프론트는 적당한 것 같습니다.

다만 문제가 현재 API 상에서 본인 체크를 하지 않나요? 혹시나 모르는 로그인 여부 체크 및 본인 댓글만 수정 가능하도록 되어야할 것 같습니다.

2017-02-22 08:56 UTC, kimtree commented on application/views/artworks/detail.twig
> +              <div class="content" id=comment+"{{ comment.id }}">
doublequote가 이상하게 들어가있습니다. 확인해주세요.

2017-02-22 12:57 UTC, junho85 commented on application/views/artworks/detail.twig
> +              <div class="content" id=comment+"{{ comment.id }}">
comment+ 부분이 잘 못 들어간듯?

2017-02-22 12:58 UTC, junho85 requested changes
남우님 지적 하신 부분은 수정 필요 할 듯

2017-02-22 13:24 UTC, mintplo requested changes

2017-02-22 13:24 UTC, mintplo commented on application/views/artworks/detail.twig
> +                    $this.parent().parent().find(".commentEditDiv").css("display", "none");
(parents 또는 closest 함수) + find 함수를 사용하는게 더 나을것 같습니다.

2017-02-22 13:24 UTC, mintplo commented on application/views/artworks/detail.twig
> +                    $this.parent().parent().parent().find(".comment").text(data.body.comment);
이 부분도 마찬가지입니다.

2017-02-22 13:24 UTC, mintplo commented on application/views/artworks/detail.twig
> +                <button class="commentEditBtn">수정</button>
이 부분은 아직 디자인이 안나와서 바뀔 여지가 있습니다~

2017-02-22 13:24 UTC, mintplo commented on application/views/artworks/detail.twig
> +              <div class="content" id=comment+"{{ comment.id }}">
_를 +로 잘못 쓰신것 같네요.

2017-02-23 00:53 UTC, Nablyy commented on application/views/artworks/detail.twig
> +              <div class="content" id=comment+"{{ comment.id }}">
제거했습니다

2017-02-23 00:55 UTC, Nablyy commented on application/views/artworks/detail.twig
> +                    $this.parent().parent().parent().find(".comment").text(data.body.comment);
parents로 할 경우 댓글이 여러개 달려있을 경우 모든 댓글을 찾기 때문에 부득이하게.....이렇게 사용했습니다ㅜㅜ 그래서 지금 각 댓글별로 id를 다는게 나은가 고민중이예요! 일단은 이렇게 올리고 개선하는 방향으로 하겠습니다.

2017-02-23 01:06 UTC, merged

2017-02-23 08:11 UTC, mintplo commented on application/views/artworks/detail.twig
> +                    $this.parent().parent().parent().find(".comment").text(data.body.comment);
각 id를 data 속성을 추가하셔서 달든 클래스로 달든 해서 타겟을 명확하게 가져가는게 좋을것 같습니다.

아무래도 뷰에서는 여러 엘리먼트들이 복잡하게 얽혀있으니 parent() 몇번 올라가면 스크립트 코드상에서는 어디까지 올라가고 무엇을 기준으로 find하는지 전혀 알기 힘들어서요.