Feature/#137 set pick to use db
yamujine/artmatch pull request #185
Opened 2017-02-22 08:48 UTC by Nablyy

#137
데이터베이스에서 pick count 가져오는 방식으로 수정했습니다.
리뷰 부탁드립니다!

2017-02-22 08:51 UTC, kimtree commented on application/models/Artwork_model.php
> +    public function get_pick_count_by_id($artwork_id) {
일단은 주 목적이 pick count에 있으니 이 쿼리들은 pick_model에 있는 것이 좋을 것 같습니다.

2017-02-22 08:52 UTC, kimtree requested changes

2017-02-22 08:52 UTC, kimtree commented on application/models/Place_model.php
> +    public function get_pick_count_by_id($place_id) {
일단은 주 목적이 pick count에 있으니 이 쿼리들은 pick_model에 있는 것이 좋을 것 같습니다.

2017-02-22 09:01 UTC, Nablyy commented
수정했습니다~

2017-02-22 09:02 UTC, Nablyy commented on application/models/Place_model.php
> +    public function get_pick_count_by_id($place_id) {
반영했습니다!

2017-02-22 09:02 UTC, kimtree commented on application/controllers/PickApi.php
>                  throw new Exception("type error. type=".$type);
별건 아니지만 이거 single quote로 변경하고, 인덴트 조정해주세요.

2017-02-22 09:03 UTC, kimtree commented on application/views/places/detail.twig
> +              console.log(data.body.pick_count);
디버깅 코드 제거해주세요.

2017-02-22 09:04 UTC, kimtree commented on application/controllers/PickApi.php
이 파일 고치시는 김에 early return 로직 리팩토링 및 deprecated된 함수 안쓰도록 변경해주시면 더 좋을 것 같습니다.

2017-02-22 12:53 UTC, junho85 approved these changes
👍

2017-02-23 01:31 UTC, Nablyy commented on application/controllers/PickApi.php
나름대로.... 수정을 해봤는데 이렇게 하는게 맞나요?

2017-02-23 05:59 UTC, kimtree commented on application/controllers/PickApi.php
@Nablyy 음 일단 기본적으로 오류 조건인 경우 먼저 리턴을 하고 나머지 로직은 else가 아닌 그냥 아래에 바로 쓰면서 맨 마지막에만 최종적으로 success 리턴을 하는 것인데 try~catch 때문에 순서 맞춰서 하긴 어려워 보이긴하네요~ 일단 이정도면 될 것 같습니다!

2017-02-23 06:01 UTC, merged