Feature/#3 develop user process
yamujine/artmatch pull request #20
Opened 2017-02-07 14:45 UTC by Genie-Youn

user관련 프로세스입니다.

- session 정책은 CI session library 사용해서 일단 패스워드를 제외한 유저정보를 넣어놨습니다..
- 이메일 인증은 회원가입시 CI email library 사용해서 email과 pk로 해시를 만든후 /users/{user_id}/invite/{hash} 구조로 링크를 전송하도록 구현했습니다. 
- gmail은 올바르게 수신이 되는데, naver/daum은 메일이 오지 않는 이슈가 있습니다. 혹시 관련해서 따로 설정해줄 것이 있나요?
- API response에 대한 정의가 필요할것 같습니다 ㅜㅜ
- validation check 를 어느수준정도로 해야할지 의견 주시면 감사하겠습니다.
 
API 명세입니다.

Signup
```http
POST /users
```
* _Request_

```json
{
"type":"0", //0-창작자 1-공간
"email":"yjs930915@gmail.com",
"password":"halim1209"
}
```

* _Response_

```json
SUCCESS { "signup success" } 
```
```json
FAIL { "duplicated email"}
```

Login
```http
POST /login
```
* _Request_

```json
{
"email":"yjs930915@gmail.com",
"password":"halim1209"
}
```

* _Response_

```json
SUCCESS { "login success" } 
```
```json
FAIL { "password incorrect || email is not found"}
```

Auth
```http
GET users/{user_id}/invite/{code}
```
* _Response_

```json
SUCCESS { "authorize success" } 
```
```json
FAIL { "authrize fail"}
```

users와 ci_sessions의 테이블 정보입니다.

```sql
DROP TABLE IF EXISTS `pickartyou`.`users` ;

CREATE TABLE IF NOT EXISTS `pickartyou`.`users` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `type` TINYINT UNSIGNED NOT NULL,
  `email` VARCHAR(45) NOT NULL COMMENT '회원이메일',
  `password` VARCHAR(255) NOT NULL COMMENT '비밀번호',
  `profile_image` VARCHAR(45) COMMENT ' 프로필이미지',
  `is_auth` TINYINT UNSIGNED NOT NULL COMMENT '이메일 인증 여부',
  `is_admin` TINYINT UNSIGNED NOT NULL COMMENT '관리자 여부',
  `join_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '가입한 날짜',
PRIMARY KEY (`idx`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `ci_sessions` (
        `id` varchar(40) NOT NULL,
        `ip_address` varchar(45) NOT NULL,
        `timestamp` int(10) unsigned default 0 NOT NULL,
        `data` blob NOT NULL,
        PRIMARY KEY (id)
)
ENGINE = InnoDB;
```

CI가 익숙치 않아 작업시간이 예상보다 미뤄져 죄송합니다.
좀 더 시간투자를.. 총체적 난국..

2017-02-08 01:39 UTC, junho85 commented
@Genie-Youn 
혹시 다음메일로 보낼때 실패 할 때 메시지가 뭐던가요? 서버에서 보내면 잘 될 수도 있습니다.
개발자PC 처럼 유동 IP 환경에서는 잘 안될 수 있습니다. ip 랑 도메인이 일치 하는지 검사 같은걸 하기 때문입니다. gmail 도 몇통 정도는 되어도 좀 보내다 보면 안될거에요.

암튼 ip 랑 도메인 받은 우리 서버에서는 잘 될겁니다. 다만 대량 발송인 경우 잘 안될 수도 있는데 그 경우 spf, dkim 등 설정이 필요 할 수 있습니다.

일단 설정이 비교적 spf 정도만 해 둬도 크게 문제는 없겠습니다. 도메인에 등록만 해 주면 되는데 이건 팀장님께 요청 해 볼게요.
spf 설정은 pickartyou.com 도메인의 TXT 레코드에 정도 추가 하면 됩니다.
"v=spf1 ip4:222.239.251.33 ~all"

dkim 은 설정이 좀 번거로운 편이라 급하지 않으면 여유가 될 때 하는게 좋겠습니다. 아직은 필요 없겠지만 혹시 나중에 대량 메일 발송 하게 되면 필요하게 될 수 있습니다.

2017-02-08 09:59 UTC, kimtree requested changes
- 현재 페이스북 로그인 > 회원가입 프로세스가 없습니다. 추가 부탁드립니다. (ion_auth 적용은 제외하신 것인가요?)
- API 관련 컨트롤들은 별도 /api 등으로 분리하는 것이 명확하지 않을까 생각이 듭니다. (response 정리도 쉽구요)
- 함수 네이밍에 신경써주시면 감사하겠습니다.
- 에디터 어떤걸 사용하시는지 모르겠지만, PSR-1/2 내용대로 코드 컨벤션 정리해주시면 좋을 것 같습니다.
- develop 브랜치 기반으로 rebase 부탁드립니다.

2017-02-08 09:59 UTC, kimtree commented on application/config/config.php
> +$config['base_url'] = 'www.pickartyou.com';
config 파일 바로 윗줄을 보시면 trailing slash까지 추가해 달라고 적혀있습니다. 제가 알기로는 http:// 프로토콜과 마지막에 / 로 끝나는게 규칙으로 알고 있는데 확인 부탁드립니다.

2017-02-08 09:59 UTC, kimtree commented on application/config/routes.php
> +$route['login']['GET'] = 'login/index';
기본 GET과 기본 route 호출은 Class/index() 함수를 호출하도록 되어있습니다. 기본 값에 대한 route 설정은 헷갈릴 수 있으므로 없는 것이 좋을 것 같습니다.

2017-02-08 09:59 UTC, kimtree commented on application/config/routes.php
> +$route['users/(:any)/invite/(:any)'] = 'users/authorize/$1/$2';
의미가 조금 헷갈립니다. 이메일 인증을 받고 접속하는 route인데 invite라는 말을 쓰고 있어서 그 의미가 잘 전달이 되지 않습니다.

2017-02-08 09:59 UTC, kimtree commented on application/controllers/Login.php
> +            'email' => $this->session->userdata('email'),
세션에 값이 없는 경우의 처리는 없을까요? 값이 없으면 $user은 있지만 email/auth가 빈 값인 배열로 넘어갈 것 같은데, 세션 여부 체크해서 아예 $user가 없는 경우 $user가 NULL이면 더 이해하기 쉬울 것 같습니다.

2017-02-08 09:59 UTC, kimtree commented on application/controllers/Users.php
> +        $this->load->helper('security');
security helper를 사용하는 함수가 보이지 않는 것 같습니다.

2017-02-08 09:59 UTC, kimtree commented on application/controllers/Users.php
> +        $this->load->library('session');
session을 사용하는 부분이 함수 1개인 것 같은데 용처가 다양하지않은 경우에는 생성자에 넣는 것이 오버헤드일 수도 있을 것 같습니다.

2017-02-08 09:59 UTC, kimtree commented on application/controllers/Users.php
> +    public function remember($user)
회원 정보를 세션에 넣는 용도로 사용하는 함수인 것 같은데 함수명이 좀 헷갈립니다. register_user_data_in_session .. 은 너무 길지만 의미가 좀 더 부여되면 좋을 것 같습니다.

2017-02-08 09:59 UTC, kimtree commented on application/models/User_model.php
> +    public function add($user){
$user을 받을 때 $user에 어떤 타입 / 어떤 key를 포함하는 애들이 들어올지 모를 것 같긴한데, 서비스 로직처럼 add가 ($name, $email, ~~ ); 등으로 파라미터를 받으면 어떨까요?

2017-02-08 09:59 UTC, kimtree commented on application/models/User_model.php
> +    public function get($email)
getUserInfoByEmail 등으로 네이밍이 되어야 할 것 같습니다.

2017-02-08 09:59 UTC, kimtree commented on application/models/User_model.php
> +    public function get($email)
아 get_user_by_email 이요ㅋㅋ

2017-02-08 09:59 UTC, kimtree commented on application/models/User_model.php
> +        if ($query->num_rows() == 0)
에러 처리는 좋은 것 같습니다. 다만, 다른 함수들도 비슷하게 에러처리를 추가해주시면 좋을 것 같습니다.

2017-02-08 10:13 UTC, Genie-Youn commented
- ion_auth 적용은 제외하였습니다. 살펴본 결과 간편히 가져다 쓰기엔 너무 방대하다고 판단하였습니다.
- facebook 로그인과 비밀번호찾기는 바로 작업하겠습니다.
- /api 등으로 분리한다는것과 response 정리가 쉽다라는 부분이 이해가 어렵습니다. ㅠㅠ 자세히 설명해 주실 수 있나요?
- 나머지는 수정후에 다시 PR하도록 하겠습니다. 감사합니다.

2017-02-08 10:27 UTC, kimtree commented
@Genie-Youn 아마 ion_auth를 쓰는게 나중에 권한 관리나 타 서비스 연동시에도 편하긴 해서 적용되면 좋을 것 같긴한데 아쉽네요~ /api로 분리하면 사람들이 URL만 보고도 json 으로 응답하는 URL endpoint라는 것을 쉽게 이해할 수 있구요. 만약에 로그인과 회원가입쪽에 다른 로직이 붙어서 json으로 응답하거나, view를 리턴하거나 리턴하는 것들이 섞일 수 있는데 /api인 것은 api인 것으로 몰아 넣으면 생성자에서 api 응답에 대한 json 형태를 만들어 놓고, 각 함수에서는 그 응답 값에 따라서 값을 넣어서 리턴하는 것으로 관리할 수 있습니다.

```php
public function __construct() {
    parent::__construct();
    header('Content-Type: application/json');
    $this->result = array('result' => false, 'errorCode' => null, 'body' => null);
}

public function test() {
    $this->result->result = true;
    $this->result->body = array('name' => 'test');
    return $this->output->set_output(json_encode($this->result));
}

```
약간 이런 식으로요~ 검색하다 보니까 아예 output에 header을 설정하는 것도 있는데 생성자에서 미리 선언되는거면 이것도 좋을 것 같네요.

```php
$this->output->set_content_type('application/json')
             ->set_output(json_encode($output));
```

2017-02-08 10:42 UTC, kimtree commented on application/controllers/Users.php
> +    public function register()
기획서 바탕으로 보면 아이디?이름? 으로 쓸 내용이 필요할 것 같습니다. 이메일 주소는 로그인할 때 쓰이지만 나중에 페이스북 회원 가입 후에 이름 가져오는 것 처럼 일반적인 가입 절차에도 이름을 받는 필드가 필요합니다.

2017-02-08 10:47 UTC, Genie-Youn commented
REST하게 설계하는것 같아서
View를 리턴하는 작업은 Signup controller와 Login controller로 위임하고
JSON을 반환하는 user 관련 API는 User controller에 작성하였는데,

말씀하신것처럼
/api라는 uri를 만들어서 UserApi controller 이런식으로 새로운 컨트롤러를 만드는게 더 나을까요??!

2017-02-08 10:50 UTC, kimtree commented
@Genie-Youn 음 위에 코멘트 드린 것 처럼 만약에 유저의 마이페이지를 만들게 되면 User Controller에 넣겠죠? 이러면 원래는 JSON만 사용하려는 컨트롤러가 view와 섞이게 되니 API는 API대로 묶는게 나을 것 같습니다!

2017-02-08 10:51 UTC, Genie-Youn commented
확인했습니다. 감사합니다!

2017-02-09 00:40 UTC, junho85 commented on application/config/routes.php
> +$route['users/(:any)/invite/(:any)'] = 'users/authorize/$1/$2';
안그래도 얼마전에 애플 계정 잠금해제에 이메일 인증 메일을 받았는데 주소가 대략 다음과 같습니다.
https://iforgot.apple.com/verify/email?key=000644-00-d6ab...
verify 는 어떤가요?

2017-02-09 00:48 UTC, junho85 approved these changes
하면서 점진적으로 개선해 나가면 되겠습니다.

2017-02-10 08:50 UTC, kimtree commented on application/controllers/Login.php
> +        if (empty($user)) {
$user에 이미 'email', 'auth' 키가 설정된 상태라 값이 NULL이 들어가도 empty($user) 판별이 정상적으로 안될 것 같습니다.
session에서 가져온 값 두개 중 하나라도 정상적이지 않으면 empty처럼 처리하는게 나을 것 같습니다.

2017-02-10 08:50 UTC, kimtree commented on application/controllers/Login.php
> +    public function __construct()
별도로 생성자 로직을 넣는게 아니라면 부모 생성자를 명시적으로 호출해줄 필요는 없을 것 같습니다.

2017-02-10 08:51 UTC, kimtree commented on application/controllers/Login.php
> +        $this->load->view('login', $user);
view 정책이 템플릿 엔진 사용하는 방법으로 바뀌었으니 MY_Controller 상속 로직으로 변경 후 $this->twig->display('템플릿 이름', $data); 와 같은 식으로 변경해주세요.

2017-02-10 08:51 UTC, kimtree commented on application/controllers/Signup.php
> +        $this->load->view('signup');
MY_Controller 상속 로직 후 twig 템플릿 엔진 사용 방법으로 변경해주세요.

2017-02-10 08:56 UTC, kimtree commented on application/controllers/UsersApi.php
> +            $this->user_model->clear_message();
user_model은 user 관련 데이터베이스 로직만 일임하는 것이 맞는 것 같습니다. API에서 사용할 output 관련 로직은 별도의 모델을 생성하거나, 현재 컨트롤러 내부에서 만들어서 관리하는 것이 좋을 것 같습니다. 예전에 만들었던 코드에서는 아래와 같이 처리하기도 했습니다.

```php
public function __construct() {
		parent::__construct();
		header('Content-Type: application/json');
		$this->result = array('result' => false, 'errorCode' => null, 'body' => null);
	}
```

2017-02-10 09:02 UTC, kimtree commented on application/controllers/UsersApi.php
> +        if (hash_equals($code, hash('ripemd160', $user['email'] . $user['id']))) {
첨에 이거 해시 알고리즘인 줄 몰랐는데.. sha1같은거 쓰면 안되려나요? 그리고 단순히 email.id 조합은 유추하기도 쉬운 string이라.. salt도 있으면 좋을 것 같습니다.

2017-02-10 09:07 UTC, kimtree commented
ci_sessions 테이블 생성 쿼리도 sql 폴더 하위에 ci_sessions.sql 등으로 넣어주세요.

2017-02-10 09:46 UTC, kimtree commented on application/config/routes.php
> +$route['api/users']['POST'] = 'usersapi/register';
api/users/register 등의 네이밍이 더 어울릴 것 같습니다. api/user 라는 내용만 봐서는 무엇을 하는 API인지 알기 어렵습니다.

2017-02-10 09:48 UTC, kimtree commented on application/config/routes.php
> +$route['api/users/(:any)/verify/(:any)'] = 'usersapi/verify/$1/$2';
지난번에 @junho85 님이 어디 코멘트 주셨던 것 같은데, 주소에 user의 id가 직접 노출되는 것은 보안상 좋지 않습니다. api/users/verify/<hash> 등의 로직으로 하고 hash는 salt와 id + email이 더해진 내용으로 생성되어야 할 것 같습니다.

2017-02-10 19:33 UTC, Genie-Youn commented
hash알고리즘 변경과 twig 적용은 내일 이어서 진행하도록 하겠습니다 :D

2017-02-11 05:21 UTC, junho85 commented
회의 한대로 hash 까지만 고치고 머지 하고 페이스북 연동은 별도 이슈에서 처리 하기로 함.

2017-02-12 06:59 UTC, kimtree approved these changes

2017-02-12 06:59 UTC, merged