apply email template 적용
yamujine/artmatch pull request #330
Opened 2017-02-27 14:22 UTC by Genie-Youn

#296 

지원 안내 메일에도 이메일 템플릿을 적용했습니다.
워딩과 디자인에 관한 논의는 추후에 더 필요할것 같습니다..

![kakaotalk_photo_2017-02-27-23-12-03](https://cloud.githubusercontent.com/assets/16642635/23364542/d4f9e122-fd42-11e6-9eef-6d8555a4798f.jpeg)
![kakaotalk_photo_2017-02-27-23-12-07](https://cloud.githubusercontent.com/assets/16642635/23364553/dca0d6c4-fd42-11e6-8f1f-7ad14f3abd24.jpeg)

2017-02-27 14:50 UTC, junho85 approved these changes
👍

2017-02-27 15:54 UTC, kimtree requested changes

2017-02-27 15:54 UTC, kimtree commented on application/libraries/Applylib.php
> +        $email_html = $this->CI->twig->render('email/apply', ['artworks' => $artworks, 'user_name' => $user_name]);
지난번에도 말씀드렸지만, accountlib도 다른 라이브러리 처럼 static한 function 처럼 구현이 되어야 합니다. $user_name을 파라미터로 받거나 $user_id를 넘기면 그 회원 정보를 조회해서 가져오는 식이 되는게 맞습니다.

2017-02-27 16:06 UTC, Genie-Youn commented on application/libraries/Applylib.php
> +        $email_html = $this->CI->twig->render('email/apply', ['artworks' => $artworks, 'user_name' => $user_name]);
수정하도록 하겠습니다~

2017-06-07 06:58 UTC, kimtree commented
이것도 rebase또는 머지 제대로 수정 좀 해주세요~ diff 보기가 좀 어려워서요~

2017-06-07 07:05 UTC, closed without merging