페이스북 access token을 long lived access token으로 변경하였습니다.
yamujine/artmatch pull request #336
Opened 2017-02-27 15:59 UTC by Genie-Youn

현재 Facebook access token을 account controller의 signup method와 usersapi controller의 register method 두군데서 사용하고 있는데 세션에 따로 저장하지 않고 필요할 때 마다 js에서 받아와 사용하려고 했습니다.

그런데 js에서 access token을 가져오는게 아니라 인증코드? 를 받아오고 이를 통해 access token을 가져오는것 같아서 확인해보니 하나의 인증코드로는 하나의 access token만을 발급받을 수 있는것 같아서.. long lived token으로 변경해 세션에 저장해두는걸로 구현하였습니다.

#304 의 This authorization code has been used error가 js에서 access token을 두번 가져오려고 할때 발생하는 에러인것 같습니다.

2017-02-27 16:19 UTC, kimtree requested changes

2017-02-27 16:19 UTC, kimtree commented on application/controllers/Account.php
> +            $longLivedAccessToken = $this->accountlib->get_facebook_access_token();
이 토큰을 $accessToken = new Facebook\Authentication\AccessToken('{example-access-token}') 로 만든다음에 isLongLived()가 맞는지, getExpiresAt()이 길게 나오는지 확인 부탁드립니다. 그리고 longLivedToken이라고 해도 언젠가는 expired될 수 있습니다. 그런 경우에 예외처리도 필요합니다.

2017-02-27 16:19 UTC, kimtree commented on application/controllers/Account.php
> +                $fb->setDefaultAccessToken($longLivedAccessToken);
longLivedToken이 사용이 종료되면 session에서 지워주는 것도 필요할 것 같습니다. 아니면 가입할 때 해당 토큰을 DB에 저장하고 추후 활용할 수 있을 것 같습니다.

2017-03-04 04:51 UTC, junho85 approved these changes
👍

2017-06-06 15:05 UTC, Genie-Youn commented on application/controllers/Account.php
> +            $longLivedAccessToken = $this->accountlib->get_facebook_access_token();
확인 완료했습니다~

2017-06-06 15:07 UTC, Genie-Youn commented on application/controllers/Account.php
> +                $fb->setDefaultAccessToken($longLivedAccessToken);
토큰이 로그인시마다 재발급되기 때문에 DB에 따로 저장하지 않고 세션내 로그인 정보들과 같은 생명주기를 갖는게 좋지 않을까요?

2017-06-06 15:15 UTC, Genie-Youn commented
향후 FB access token이 언제 또 사용될지 생각해보았습니다.
기획엔 없지만 아마 전시내용이나 작품을 페이스북 타임라인에 공유하기 정도로 사용될 것 같은데,

세션에서 토큰을 가져올때 라이브러리에서 만료된 토큰일 경우 null을 반환하고
이를 사용하는 비즈니스 로직에서 토큰이 없을경우 페이스북 로그인을 하게 만드는게 좋을 것 같아서 일단 null을 반환하는 정도로 수정하였습니다.

현재 세션 유지 시간은
CI 세션 유지 시간 (2시간) / 페이스북 LongLivedToken의 유지 시간 (2개월) 입니다.

2017-06-07 06:56 UTC, kimtree commented
diff보기가 좀 어려운데 머지 또는 rebase 좀 부탁드립니다~

2017-06-09 15:04 UTC, closed without merging