Enhanced/#335 fix facebook sdk error
yamujine/artmatch pull request #371
Opened 2017-06-16 11:50 UTC by Genie-Youn

#335 

Facebook response exception 에 대한 처리입니다.

UsersApi 에선 코드레벨에서 해줄 수 있는 예외처리가 없기 때문에 로그를 남긴 후 fail을 리턴하도록 구현하였습니다.

이슈에 있었던 Account에서는 페이스북으로 회원가입을 눌러놓고 앱관리에서 앱을 지운 뒤 새로고침을 하는 등 임의적인 조작이 있을 경우 나타나는것 같아서 main으로 redirect 시키도록 구현하였습니다.

2017-06-20 07:16 UTC, kimtree commented on application/controllers/Account.php
> +                    if ($userNode === NULL) {
$response를 보니까 isError 함수 같은게 있는데 이 함수를 이용해서 조건문을 처리하면 의미가 좀 더 명확해 질 것 같습니다!

2017-06-20 07:17 UTC, kimtree commented on application/controllers/Account.php
> +                    $data['facebook_profile_image_url'] = $userNode->getPicture()->getUrl();
getPicture함수가 null을 리턴할 수도 있는데 이에 대한 처리도 있으면 좋을 것 같습니다.
userNode->getPicture가 !== 이면 getURL 값을 사용하는 식으로

2017-06-20 07:17 UTC, kimtree commented on application/controllers/Account.php
> +                    $userNode = $response->getGraphUser();
네이밍을 user_node 식으로 변경해주세요~

2017-06-20 07:18 UTC, kimtree commented on application/controllers/UsersApi.php
> +            log_message("error", "FaceBook SDK Exception : " . $e->getMessage());
일반적 스트링은 single quote 사용해주세요~

2017-06-20 07:18 UTC, kimtree commented on application/controllers/Account.php
> +                    log_message("error", "FaceBook SDK Exception : " . $e->getMessage());
여기도 single quote로

2017-06-20 07:21 UTC, kimtree requested changes
페이스북 SDK가 좀 지저분 한 느낌인데...ㅋㅋ 에러 체크하고 exception throw하는 쪽만 좀 더 깔끔하게 정리만 되면 좋을 것 같습니다!

2017-07-09 06:48 UTC, kimtree requested changes

2017-07-09 06:48 UTC, kimtree commented on application/controllers/UsersApi.php
> +            if ($user_node === NULL) {
다른 곳에선 $response->isError(); 함수를 사용하고 있는데 여기도 비슷하게 구현되면 좋을 것 같습니다.

2017-07-09 06:48 UTC, kimtree commented on application/controllers/UsersApi.php
> +        $this->return_success_response(['message' => '입력하신 이메일로 임시 비밀번호를 보내드렸습니다.\n메일함을 확인해주세요.']);
\n 쓸 때 single quote써도 되는지 헷갈리네요. 한 번 확인 부탁드립니다!

2017-07-09 06:48 UTC, kimtree commented on application/controllers/UsersApi.php
> +        if (empty($user_node->getEmail())) {
권한 체크 부분을 try~catch 부분 안쪽으로 옮겨서 새로운 Exception 정의 후 throw 해주어도 좋을 것 같습니다!

2017-07-09 07:57 UTC, Genie-Youn commented on application/controllers/UsersApi.php
> +        $this->return_success_response(['message' => '입력하신 이메일로 임시 비밀번호를 보내드렸습니다.\n메일함을 확인해주세요.']);
\n은 안되네요ㅋㅋ 수정해서 올릴께욥

2017-07-09 08:07 UTC, kimtree approved these changes

2017-07-09 08:07 UTC, merged