feature/#10_artwork_list
yamujine/artmatch pull request #40
Opened 2017-02-10 07:38 UTC by Nablyy

작품 리스트 확인할 수 있도록 만들었습니다.
준호님 코드 많이 참고했어요!!
너무 심하게 복붙 신공을 한 것 같아 죄송하네요ㅜㅜ
남우님이 먼저 작품 등록을 완성하셔서 그 위에 덧붙였는데 뭔가 잘못 건드려 문제가 생겼을까 매우 걱정이 됩니다.
제가 php를 처음 다뤄봐서 열심히 공부하고는 있는데 부족한 부분이 많아요.
피드백 주시면 바로 수정하도록 하겠습니다!

2017-02-10 09:17 UTC, kimtree approved these changes
간단한거만 수정하고 바로 머지해도 될 것 같습니다.

2017-02-10 09:17 UTC, kimtree commented on application/controllers/Artworks.php
> +			$this->load->database();
일단 database 로직은 autoload.php에 추가해놔서 여기선 빼도 될 것 같습니다!

2017-02-10 09:17 UTC, kimtree commented on application/controllers/Artworks.php
> +			$data = ['test' => true, 'artworks' => $artworks];
'test' 파라미터는 빼셔도 됩니다~

2017-02-10 09:17 UTC, kimtree commented on application/models/Artwork_model.php
> +	function __construct() {
constructor은 빼도 됩니다~

2017-02-10 14:40 UTC, junho85 commented on application/controllers/Artworks.php
> +			$data = ['test' => true, 'artworks' => $artworks];
아 요거 Places.php 쪽도 빼야 되겠음.

2017-02-10 14:43 UTC, junho85 requested changes
남우님이 말씀하신것을 수정 해 주시면 되겠습니다.

2017-02-10 14:43 UTC, junho85 commented on application/controllers/Artworks.php
> +			$this->load->database();
오 그렇군요. Places 쪽도 빼야 겠네요.

2017-02-11 06:21 UTC, Nablyy commented
리뷰감사합니다!
리뷰해주신 부분 적용해서 커밋했습니다~

2017-02-11 06:22 UTC, kimtree commented on application/models/Artwork_model.php
> +			return $this->db->get('artworks')->result();
'artworks' $this::TABLE_NAME 써주세요~

2017-02-11 06:49 UTC, merged