Improvement/#419 manage exhibition
yamujine/artmatch pull request #423
Opened 2017-07-26 07:37 UTC by kimtree

#419 에 있는 개선사항을 적용한 PR입니다.

2017-07-26 08:51 UTC, mintplo approved these changes
디자인 관련 이슈는 확인해보고 다른 브랜치에서 해결하겠습니다.

2017-07-26 09:03 UTC, mintplo requested changes
트윅 오타만 수정하시면 될것 같습니다.

2017-07-26 09:03 UTC, mintplo commented on application/views/places/exhibitions.twig
> +        {% if exhibitons.length > 0 %}
exhibitions|length 로 바꿔주세요.

2017-07-28 07:00 UTC, kimtree commented on application/views/places/exhibitions.twig
> +        {% if exhibitons.length > 0 %}
@mintplo 해결!

2017-07-28 07:16 UTC, junho85 approved these changes
👍

2017-07-28 07:19 UTC, mintplo approved these changes

2017-07-28 07:39 UTC, merged