Feature/#53 comment api
yamujine/artmatch pull request #63
Opened 2017-02-12 17:19 UTC by Nablyy

comment api 기능들을 구현해봤는데 심각하네요.
만든 코드라도 리뷰를 받기 위해 풀리퀘를 올립니다.
이렇게 하는게 맞는지 잘 모르겠는데 일단 원하는대로는 동작합니다.

- list: $type(그림인지 장소인지 여부), $type_id 받아와서 해당 코멘트들 목록 보여줌
- insert: $type, $user_id, $type_id, $comment 받아와서 코멘트 insesrt
- update: $type, $type_comment_id, $comment 받아와서 해당 코멘트 update
- delete: $type, $type_comment_id 받아와서 해당 코멘트 delete

2017-02-12 17:45 UTC, kimtree requested changes

2017-02-12 17:45 UTC, kimtree commented on application/controllers/CommentApi.php
> +class CommentApi extends CI_Controller {
제가 API 관련 클래스 개선을 좀 했는데요~ API_Controller 상속 받아서 쓰면 성공/실패 response 간단한 처리 로직 포함되게 했는데 그 틀에 맞춰서 수정해 주시면 감사하겠습니다!

2017-02-12 17:45 UTC, kimtree commented on application/config/routes.php
> +$route['api/comment'] = 'commentapi';
아무 기능을 하지 않는 route로 보입니다!

2017-02-12 17:45 UTC, kimtree commented on application/controllers/CommentApi.php
> +    public function index() {
아무 기능을 하지 않는 function으로 보입니다!

2017-02-12 17:45 UTC, kimtree commented on application/controllers/CommentApi.php
> +        $user_id = 9282;
$user_id(user 테이블의 PK) 가져오는 것은 $this->logincheck->get_user_id() 함수를 활용하면 좋을 것 같습니다.

2017-02-12 17:45 UTC, kimtree commented on application/models/Comment_model.php
> +			throw new Exception("type error. type=".$type);
Exception 사용하는 로직은 좋은데 get_comments_by_type_id를 호출하는 부분에서 try ~ catch 블락이 없습니다. 확인 부탁드립니다.

2017-02-12 17:45 UTC, kimtree commented on application/controllers/CommentApi.php
> +		$result_id = $this->comment_model->delete_comment($type, $type_comment_id);
실제로 delete_comment 함수의 리턴값이 $result_id 가 아니라 $affected_rows니까 네이밍 수정이 필요해보입니다.

2017-02-13 04:54 UTC, junho85 requested changes
공백에 스페이스와 탭이 혼용 되어 있어서 보기가 조금 불편하네요. 스페이스로 통일했으면 좋겠습니다.

2017-02-13 09:08 UTC, mintplo requested changes
PHPStorm Reformat Code 한번만 부탁드립니다.

+ artwork, place 구분을 위해 type을 사용하는데 상수 처리가 나아보입니다. 이 부분은 @kimtree 님께서 작업하신걸로 알고 있는데 맞나요?

2017-02-13 09:08 UTC, mintplo commented on application/controllers/CommentApi.php
> +        $comments = $this->comment_model->get_comments_by_type_id($type, $type_id);
컨트롤러에서 Request Parameter를 받아(컨트롤러 처리) 값을 가져올 때 (모델 처리) Response를 내려 줄 때 (컨트롤러 처리) 문맥상 다릅니다. 라인을 나누어 BLOCK 별로 구분짓는게 나을것 같습니다. (여기는 단순하지만 추후에 컨트롤러에서 더 복잡한 + 긴 처리가 필요할 경우 코드 팔로우가 힘들어집니다~)

2017-02-13 09:08 UTC, mintplo commented on application/controllers/CommentApi.php
> +				$this->response_success(array('type' => $type, 'type_comment_id' => $type_comment_id, 'result_id' => $result_id, 'comment' => $comment, 'result_type' => "update"));
repsonse_success 라는 이름이 당장 결과를 내려주는지 아니면 결과 값을 SET 해주는지 판단하기 어렵습니다. 위에 @kimtree 님이 말씀해주신것처럼 대응해주시면 좋을것같습니다.

2017-02-13 09:08 UTC, mintplo commented on application/controllers/CommentApi.php
> +        if($result_id) {
실제로 모델에 정상적으로 처리가 되었는지 ID를 확인하는 로직이 메소드별로 제각각인 것 같습니다. 가이드나 룰 제정이 필요할것으로 보입니다.

0,FALSE,null 을 처리하는 empty() 사용을 강제하거나
!== (type checking 까지 하는 comparison operator 사용을 강제하거나) 어떻게 생각하시나요?

@kimtree @junho85 @Genie-Youn @Nablyy

2017-02-13 09:08 UTC, mintplo commented on application/models/Comment_model.php
> +			throw new Exception("type error. type=".$type);
예외 처리 메시지는 나중에 수정하실건가요? 잘못 처리할 경우 예외 메시지가 그대로 서비스에 노출됩니다.

2017-02-13 09:08 UTC, mintplo commented on application/models/Comment_model.php
> +	    $data = array(
array 사용 보다 [] 이걸 사용하는게 어떨까요?

2017-02-13 09:08 UTC, mintplo commented on application/models/Comment_model.php
> +		if($this->db->set(array('comment' => $comment))
쿼리 빌더 체이닝 로직을 if 안에 넣어 처리하는것보다 $result 변수를 한번 더 사용하는 것이 읽히기 더 좋을것 같습니다.

2017-02-13 09:54 UTC, kimtree commented on application/controllers/CommentApi.php
> +        if($result_id) {
전 추천!

2017-02-13 12:40 UTC, junho85 commented on application/controllers/CommentApi.php
> +        if($result_id) {
다른 곳에서는 필요할거 같기도 한데 if ($result_id) 정도는 별 문제될 부분처럼 보이지는 않습니다.
게다가 is_empty 도 아니고 empty 라니. 뭔가 함수 이름이 짓다 만 느낌 ㅡ,.ㅡ; 혼란의 여지를 줄여 주는 곳에서의 적절한 사용은 좋지만 일단 empty 도 별로 마음에 안들고 !== 같은 타입 체킹을 하자니 쓸데 없이 코드가 너저분해 지는 느낌입니다.

2017-02-16 13:16 UTC, junho85 commented on application/config/routes.php
> +$route['api/comment'] = 'commentapi';
comment -> comments
api/comments 를 list 조회 용도로 하고 comment/list 는 제거 하겠습니다.

2017-02-16 13:23 UTC, junho85 commented on application/controllers/CommentApi.php
> +class CommentApi extends CI_Controller {
API_Controller
```
    public function set_success_response($body) {
        $this->result['result'] = true;
        $this->result['body'] = $body;
    }

    public function set_fail_response($error_code, $body) {
        $this->result['result'] = false;
        $this->result['errorCode'] = $error_code;
        $this->result['body'] = $body;
    }
```

사용예는 UsersApi 참고

$this->set_fail_response('101', ['message' => 'duplicated email']);
$this->set_success_response(['message' => 'signup success']);

2017-02-16 13:24 UTC, junho85 commented on application/controllers/CommentApi.php
> +    public function index() {
list 를 여기로 넣겠습니다.

2017-02-16 13:24 UTC, junho85 commented on application/controllers/CommentApi.php
> +        $this->output->set_content_type("application/json");
API_Controller 사용하면서 이 라인은 제거

2017-02-16 13:24 UTC, junho85 commented on application/controllers/CommentApi.php
> +        $user_id = 9282;
리스트 조회 하는데 $user_id 가 필요 없어서 제거

2017-02-16 13:26 UTC, junho85 commented on application/controllers/CommentApi.php
> +        $comments = $this->comment_model->get_comments_by_type_id($type, $type_id);
음; 무슨말씀인지 잘 몰르겠습니다;

2017-02-16 13:27 UTC, junho85 commented on application/controllers/CommentApi.php
> +				$this->response_success(array('type' => $type, 'type_comment_id' => $type_comment_id, 'result_id' => $result_id, 'comment' => $comment, 'result_type' => "update"));
done

2017-02-16 13:29 UTC, junho85 commented on application/controllers/CommentApi.php
> +		$result_id = $this->comment_model->delete_comment($type, $type_comment_id);
$affected_rows 로 변경

2017-02-16 13:30 UTC, junho85 commented on application/controllers/CommentApi.php
> +        if($result_id) {
일단 다른 부분은 다 $result_id !== NULL 이라서 통일

2017-02-16 13:36 UTC, junho85 commented on application/models/Comment_model.php
> +			throw new Exception("type error. type=".$type);
CommentApi 에 try catch 구문 추가

2017-02-16 13:37 UTC, junho85 commented on application/models/Comment_model.php
> +			throw new Exception("type error. type=".$type);
메시지는 따로 정리가 필요 해 보입니다.

2017-02-16 13:40 UTC, junho85 commented on application/models/Comment_model.php
> +	    $data = array(
고칠게 많군요 덜덜
하지만 phpstrom 과 함께라면 두렵지 않아!
![image](https://cloud.githubusercontent.com/assets/1219373/23023415/e0b547a2-f498-11e6-9a10-577759955eb5.png)

2017-02-16 13:42 UTC, junho85 commented on application/models/Comment_model.php
> +		if($this->db->set(array('comment' => $comment))
👍

2017-02-16 13:51 UTC, merged