Feature/#68_user_sign_up
yamujine/artmatch pull request #90
Opened 2017-02-14 08:59 UTC by mintplo

#68
메인 - 회원 가입
회원가입
로그인

작업한 내용 PR

2017-02-14 09:00 UTC, kimtree commented on application/views/account/login.twig
> +		$('#patLoginForm').submit(function () {
pat~ 네이밍은 어떤 의미인가요?

2017-02-14 09:01 UTC, kimtree commented on application/views/signup.twig
> +{% extends "base.twig" %}
현재 /views/signup.twig가 따로 필요한 이유가 있나요? 아마 기존의 파일인 것 같은데 업로드 되면 안될 것 같습니다.

2017-02-14 09:01 UTC, mintplo commented on application/views/account/login.twig
> +		$('#patLoginForm').submit(function () {
pick art you 각 앞글자를 따서 custom하게 스타일을 입히기 위한 클래스 네이밍입니다.

2017-02-14 09:02 UTC, kimtree requested changes
/views/signup.twig 추가된 것 지워져야 할 것 같고, signup.twig는 컨플릭트 미리 해결 부탁드립니다.

2017-02-14 09:02 UTC, mintplo commented on application/views/signup.twig
> +{% extends "base.twig" %}
@kimtree 
회원가입이 2개의 형태입니다.
기획서 보시면

메인 화면에서 signup -> 계속하기 버튼 -> 회원가입 페이지로 이동

로그인 -> 회원가입 버튼 클릭 -> 회원가입 페이지

인데 하나로 통합할수 없어서 따로 만들었습니다. 확인 후 이에 대한 의견 부탁드립니다.

2017-02-14 09:03 UTC, mintplo commented on application/views/signup.twig
> +{% extends "base.twig" %}
두 개의 타입이 디자인도 다르구요

2017-02-15 00:23 UTC, junho85 commented on application/views/account/login.twig
> +		$('#patLoginForm').submit(function () {
음. 저는 전에 환경 변수를 앞자 따서 PAY 라고 했었는데요. 뭔가 통일을 해야 될거 같긴 합니다. 앞자만 따면 PAY 인데 이게 영어 단어가 연상 되어서 좀 이상하긴 함. PAT 으로 통일?

2017-02-15 00:24 UTC, junho85 commented on assets/scss/main/signup.scss
> +  background: url('http://cdn.bizwatch.co.kr/news/photo/2015/05/26/26c044343ef504b2ff1ba81c17577deb150333.jpg') center center no-repeat;
혹시 저작권 문제는 없는 이미지인가요?

2017-02-15 01:32 UTC, mintplo commented on assets/scss/main/signup.scss
> +  background: url('http://cdn.bizwatch.co.kr/news/photo/2015/05/26/26c044343ef504b2ff1ba81c17577deb150333.jpg') center center no-repeat;
일단 테스트로 넣어놓은것이라 나중에 변경할 예정입니다!

2017-02-15 11:42 UTC, merged