Feature/#66 develop private my page
yamujine/artmatch pull request #94
Opened 2017-02-16 07:29 UTC by Genie-Youn

#66 

my private page의 프로필사진 변경 & 비밀번호 변경 PR 입니다.

2017-02-16 15:05 UTC, kimtree requested changes

2017-02-16 15:05 UTC, kimtree commented on application/controllers/UsersApi.php
> +        $this->load->library('imageupload', 'upload');
Imageupload 라이브러리는 생성자에 이미 선언된 라이브러리이고, upload 라이브러리는 사용처가 안보이는데 확인 부탁드립니다.

2017-02-16 15:05 UTC, kimtree commented on application/controllers/UsersApi.php
> +            $this->user_model->update_profile_image(
현재는 무조건 업데이트를 하는 구조인데 프로필 사진을 제거하는 일은 없을테니, $uploaded_image_name인 경우만 DB를 업데이트 하는 것이 좋을 것 같습니다.

2017-02-16 15:05 UTC, kimtree commented on application/controllers/UsersApi.php
> +                if ($this->user_model->update_password($this->accountlib->get_user_id(), $hashed_password) !== NULL) {
if문의 조건문이 알아보기 힘든데 model의 함수를 요청하는 부분은 $result등으로 별도 변수화 시킨 후 비교하면 좋을 것 같습니다.

2017-02-16 15:05 UTC, kimtree commented on application/models/User_model.php
> +            return $id;
딱히 리턴값인 $id를 활용하는 로직은 없어보이는데, return $this->db->update~ 식으로 구현해도 괜찮을 것 같습니다.

2017-02-16 15:05 UTC, kimtree commented on application/models/User_model.php
> +            return $id;
상동

2017-02-16 15:05 UTC, kimtree commented on application/views/users/mypage.twig
> +                    location.href = '/users/me';
성공적으로 변경된 경우 유저에게 성공적으로 변경되었는지 알려주는 것이 좋은 UX아닐까요? 단순히 화면이 새로고침되면 정상적으로 처리된 것인지 인지하기 어려울 것 같습니다.

2017-02-16 15:05 UTC, kimtree commented on application/views/users/mypage.twig
> +    <div class="modal fade" id="profile_modal" tabindex="-1" role="dialog">
모달뷰도 look & feel이 통일되어야 할 듯 한데 @mintplo 님과 상의하여 조절하시면 좋을 것 같습니다.

2017-02-16 15:05 UTC, kimtree commented on application/views/users/mypage.twig
> +           $('#profile_change_form').submit();
프로필 변경 로직도 패스워드 변경처럼 ajax로 처리하여 성공 값을 전달 받고 모달이 사라진 상태에서 보여지는 화면의 이미지를 교체하는 방식으로 통일되는 것이 괜찮아 보입니다.

2017-02-17 01:32 UTC, junho85 approved these changes
👍

2017-02-19 06:55 UTC, Genie-Youn commented on application/controllers/UsersApi.php
> +        $this->load->library('imageupload', 'upload');
done

2017-02-19 06:55 UTC, Genie-Youn commented on application/controllers/UsersApi.php
> +            $this->user_model->update_profile_image(
done

2017-02-19 06:55 UTC, Genie-Youn commented on application/controllers/UsersApi.php
> +                if ($this->user_model->update_password($this->accountlib->get_user_id(), $hashed_password) !== NULL) {
done

2017-02-19 06:55 UTC, Genie-Youn commented on application/models/User_model.php
> +            return $id;
done

2017-02-19 06:55 UTC, Genie-Youn commented on application/views/users/mypage.twig
> +                    location.href = '/users/me';
done

2017-02-19 06:55 UTC, Genie-Youn commented on application/views/users/mypage.twig
> +           $('#profile_change_form').submit();
done

2017-02-19 07:13 UTC, kimtree requested changes

2017-02-19 07:13 UTC, kimtree commented on application/config/routes.php
> +$route['api/users/update/image']['POST'] = 'usersapi/update_profile_image';
다른 route와 일관성 유지를 위해서 update_image, change_password 등으로 사용하는 것이 좋아보입니다.

2017-02-19 07:13 UTC, kimtree commented on application/controllers/UsersApi.php
> +        if ($this->input->method() === 'post') {
route에서 POST 체크를 해서 여기나 route나 둘 중 하나에서만 method 체크를 해도 좋을 것 같습니다.

2017-02-19 07:13 UTC, kimtree commented on application/controllers/UsersApi.php
> +        if ($this->input->method() === 'post') {
여기도 route에서 이미 method 체크를 하고 있는 부분입니다.

2017-02-19 07:13 UTC, kimtree commented on application/controllers/UsersApi.php
> +            $user = $this->user_model->get_by_id($this->accountlib->get_user_id());
get_user_id 사용하는 부분이 두개가 있는데 따로 변수화 하면 코드 읽기가 편할 것 같습니다.

2017-02-19 07:13 UTC, kimtree commented on application/models/User_model.php
> +        if ($this->db->update(self::TABLE_NAME, ['profile_image' => $profile_image], ['id' => $id])) {
데이터 베이스 사용 관련해서 어제 회의 끝나고 결정된 사항이 있습니다. update인 경우는 affected rows를 체크하여 true/false 리턴을 하도록 하였습니다. 확인 후 수정 부탁드립니다. https://github.com/yamujine/artmatch/wiki/DB-%EC%BF%BC%EB%A6%AC-%EA%B7%9C%EC%B9%99

2017-02-19 07:13 UTC, kimtree commented on application/views/users/mypage.twig
> +              location.href = '/users/me';
비밀번호를 변경하는 경우는 별도로 리프레시가 없어도 되지 않나요?

2017-02-19 07:32 UTC, Genie-Youn commented on application/config/routes.php
> +$route['api/users/update/image']['POST'] = 'usersapi/update_profile_image';
done

2017-02-19 07:33 UTC, Genie-Youn commented on application/controllers/UsersApi.php
> +        if ($this->input->method() === 'post') {
done

2017-02-19 07:33 UTC, Genie-Youn commented on application/controllers/UsersApi.php
> +        if ($this->input->method() === 'post') {
done

2017-02-19 07:33 UTC, Genie-Youn commented on application/controllers/UsersApi.php
> +            $user = $this->user_model->get_by_id($this->accountlib->get_user_id());
done

2017-02-19 07:33 UTC, Genie-Youn commented on application/models/User_model.php
> +        if ($this->db->update(self::TABLE_NAME, ['profile_image' => $profile_image], ['id' => $id])) {
done

2017-02-19 07:33 UTC, Genie-Youn commented on application/views/users/mypage.twig
> +              location.href = '/users/me';
done

2017-02-19 07:50 UTC, kimtree approved these changes
간단한 사항이니 수정 후 일단은 머지해야할 것 같습니다.

2017-02-19 07:50 UTC, kimtree commented on application/controllers/UsersApi.php
> +        if ($result === TRUE) {
=== TRUE 체크는 불필요한 비교입니다. if ($result) 라도 충분합니다.

2017-02-19 07:50 UTC, kimtree commented on application/controllers/UsersApi.php
> +            if ($result === TRUE) {
t/f === TRUE 비교 구문 -> if ($result)로도 충분합니다.

2017-02-19 07:50 UTC, kimtree commented on application/config/routes.php
> +$route['api/users/change_password']['POST'] = 'usersapi/update_password';
함수명도 함께 바꿔 주시면 좋을 것 같습니다.

2017-02-19 07:57 UTC, Genie-Youn commented on application/controllers/UsersApi.php
> +        if ($result === TRUE) {
done

2017-02-19 07:57 UTC, Genie-Youn commented on application/controllers/UsersApi.php
> +            if ($result === TRUE) {
done

2017-02-19 07:57 UTC, Genie-Youn commented on application/config/routes.php
> +$route['api/users/change_password']['POST'] = 'usersapi/update_password';
done

2017-02-19 07:59 UTC, merged