Feature/#52 develop find password
yamujine/artmatch pull request #95
Opened 2017-02-16 12:28 UTC by Genie-Youn

#52 비밀번호찾기 기능 구현

이메일을 입력하면 8글자의 문자열 난수를 생성하여 비밀번호를 초기화 한뒤 메일을 발송합니다.
view는 account/reset_password로 임시로 작성해 두었습니다.

2017-02-16 15:08 UTC, kimtree commented on application/controllers/Account.php
> +    public function reset_password() {
기획서 상의 팝업이 모달뷰를 지칭하는 것 같은데 (그림 상으로 보아도) api 방식으로 작성이 되고, login.twig에 기능이 붙여져야 할 것 같습니다.

2017-02-16 15:12 UTC, kimtree commented on application/controllers/Account.php
> +            $temp_password = random_string('alpha', 8);
디테일한 내용이라 중요할지는 모르겠지만, 'alpha'로 사용하였으니 UI상에 문구로 알파벳 문자로만 되어있다고 알려주면 좋을 것 같습니다. 알파벳 o와 숫자 0이 헷갈릴 수 있습니다.

2017-02-16 15:13 UTC, kimtree commented on application/controllers/Account.php
> +            $id = $user->id;
사용처가 한 곳 밖에 되지 않으므로 변수화 하지 않고 바로 $user->id를 활용해도 될 것 같습니다.

2017-02-16 15:13 UTC, kimtree commented on application/controllers/Account.php
> +            $this->accountlib->send_email_temp_password($email, $temp_password);
혹시 모를 DB 오류에 대비해서 update_password가 정상적으로 된 경우에 메일을 발송하는 것이 좋을 것 같습니다.

2017-02-16 15:14 UTC, kimtree commented on application/libraries/Accountlib.php
> +        $email_html = $this->CI->twig->render('email/temp_password', $data);
변수가 간단한 경우는 $data를 따로 만들 필요 없이 ['temp_password' => $temp_password]를 넘겨도 문제 없을 것 같습니다.

2017-02-16 15:15 UTC, kimtree commented on application/models/User_model.php
> +            return $id;
이전 리뷰 내용과 동일하게 return된 $id를 사용하는 것이 아니면 True/False 리턴으로도 충분할 것 같습니다.

2017-02-16 15:15 UTC, kimtree commented on application/views/email/temp_password.twig
> +pickartyou 임시비밀번호 : {{ temp_password }}
로그인 링크도 함께 제공하면 좋을 것 같습니다.

2017-02-16 15:29 UTC, kimtree requested changes
리뷰 내용 확인 부탁드립니다.

2017-02-17 01:31 UTC, junho85 approved these changes
👍

2017-02-18 06:11 UTC, Genie-Youn commented on application/controllers/Account.php
> +    public function reset_password() {
done

2017-02-18 06:11 UTC, Genie-Youn commented on application/controllers/Account.php
> +            $temp_password = random_string('alpha', 8);
done

2017-02-18 06:11 UTC, Genie-Youn commented on application/controllers/Account.php
> +            $id = $user->id;
done

2017-02-18 06:11 UTC, Genie-Youn commented on application/controllers/Account.php
> +            $this->accountlib->send_email_temp_password($email, $temp_password);
done

2017-02-18 06:13 UTC, Genie-Youn commented on application/libraries/Accountlib.php
> +        $email_html = $this->CI->twig->render('email/temp_password', $data);
done

2017-02-18 06:13 UTC, Genie-Youn commented on application/models/User_model.php
> +            return $id;
done

2017-02-18 06:13 UTC, Genie-Youn commented on application/views/email/temp_password.twig
> +pickartyou 임시비밀번호 : {{ temp_password }}
done

2017-02-18 06:14 UTC, Genie-Youn commented
리뷰내용 반영했습니다._.

2017-02-18 08:01 UTC, kimtree approved these changes

2017-02-18 08:02 UTC, merged