Pick API 버그 수정 #93
yamujine/artmatch pull request #97
Opened 2017-02-16 15:18 UTC by junho85

#93

2017-02-16 15:25 UTC, kimtree commented on application/models/Artwork_model.php
> +            ->limit(1)
id가 이미 PK라서 limit(1)이 필요할까요?

2017-02-16 15:26 UTC, kimtree commented on application/models/Pick_model.php
>  	    if ($type === "artwork") {
별건 아니지만 PHP에서 모든 스트링은 single quote로 써주시면 좋을 것 같습니다.

2017-02-16 15:26 UTC, kimtree commented on application/models/Pick_model.php
해당 파일내 다른 부분도 indent 함께 수정되면 좋을 것 같습니다.

2017-02-16 15:28 UTC, kimtree commented on application/models/Place_model.php
> +            ->limit(1)
PK를 where절에 쓰는데 limit(1)인 부분입니다. Artwork model과 함께 확인 부탁드립니다.

2017-02-16 15:29 UTC, kimtree requested changes
리뷰 내용 확인 부탁드립니다.

2017-02-17 01:09 UTC, junho85 commented on application/models/Pick_model.php
>  	    if ($type === "artwork") {
single quote 로 통일 하면 검색도 편하고 $ 변수 사용하는 실수도 줄일수 있겠네요.
사실 요런건 const 로 빼는게 더 좋을 듯 하네요.

2017-02-17 01:10 UTC, junho85 commented on application/models/Pick_model.php
👍

2017-02-17 01:11 UTC, junho85 commented on application/models/Pick_model.php
@Nablyy 혹시 가능 하시면 phpstorm 학생 무료 라이센스 되면 하나 신청 해 두세요 ㅎㅎ

2017-02-17 01:14 UTC, junho85 commented on application/models/Artwork_model.php
> +            ->limit(1)
필요는 없지만 형식적으로 데이터 존재여부를 판단하기 위한 쿼리라는걸 보기 좋습니다.

2017-02-17 01:29 UTC, junho85 commented
indent 적용 등으로 컨플릭 등 이슈가 있어 일단 merge 하겠습니다. 추가 수정 필요한 부분은 이슈 만들어 주세요~

2017-02-17 01:29 UTC, merged

2017-02-17 05:07 UTC, kimtree commented on application/models/Artwork_model.php
> +            ->limit(1)
@junho85 사실 이 부분의 명시성은 하단의 num_rows를 확인하는 방법을 사용하지 않고, $query->get()->row()로도 t/f 리턴을 받을 수 있기 때문에 쿼리빌더를 통한 명확한 방법으로 간략화 할 수 있을 것으로 보입니다!